"""
A17 CodeGenerator — SINGLE RESPONSIBILITY: Generate code from templates + requirements.

Deterministic code generation: Python/Kotlin/Go/JavaScript module templates.
No AI. Template library with placeholder substitution.
"""

from __future__ import annotations

import re
from typing import Any, Dict, List

from ..resilience import BaseAgent
from ..schemas import CodeResult


# ──────────────────────────────────────────────────────────────
# CONSTANTS
# ──────────────────────────────────────────────────────────────

LANG_EXTENSIONS = {
    "python": ".py", "kotlin": ".kt", "go": ".go",
    "javascript": ".js", "typescript": ".ts", "java": ".java",
}

SUPPORTED_LANGUAGES = frozenset(LANG_EXTENSIONS.keys())

# Stop words for safe name generation
STOP_WORDS = frozenset({
    'un', 'una', 'el', 'la', 'los', 'las', 'a', 'de', 'del',
    'en', 'por', 'para', 'con', 'that', 'the', 'a', 'an',
    'create', 'make', 'generate', 'build', 'write',
})


class CodeGenerator(BaseAgent[CodeResult]):
    """
    A17: Generate code from templates + requirements.

    Single Responsibility: Code generation ONLY.
    Method: Template library lookup + placeholder substitution.
    Fallback: Empty CodeResult with no code.
    """

    def __init__(self, **kwargs):
        super().__init__(name="A17_CodeGenerator", **kwargs)

    def execute(self, input_data: Any) -> CodeResult:
        """
        Generate code from requirements and language.

        Input (CodeRequest or dict):
            - requirements: str (what to generate)
            - language: str (python|kotlin|go|javascript|typescript|java)
            - constraints: dict (optional generation constraints)

        Output: CodeResult with generated code.
        """
        if hasattr(input_data, "requirements"):
            requirements = getattr(input_data, "requirements", "")
            language = getattr(input_data, "language", "python")
        elif isinstance(input_data, dict):
            requirements = input_data.get("requirements", "")
            language = input_data.get("language", "python")
        else:
            requirements = str(input_data)
            language = "python"

        language = language.lower()
        if language not in SUPPORTED_LANGUAGES:
            language = "python"

        safe_name = self._safe_name(requirements)

        # Route to language-specific generator
        if language == "python":
            code = self._gen_python(safe_name, requirements)
        elif language == "kotlin":
            code = self._gen_kotlin(safe_name)
        elif language == "go":
            code = self._gen_go(safe_name)
        elif language in ("javascript", "typescript"):
            code = self._gen_js(safe_name)
        else:
            code = self._gen_python(safe_name, requirements)

        return CodeResult(
            code=code,
            language=language,
            files=[{"path": f"{safe_name}{LANG_EXTENSIONS.get(language, '.py')}", "content": code}],
            source="deterministic",
        )

    @staticmethod
    def _safe_name(text: str) -> str:
        """Convert text to safe module name."""
        name = re.sub(r'[^\w]', '_', text.lower().strip())
        name = re.sub(r'_+', '_', name).strip('_')
        parts = [p for p in name.split('_') if p and p not in STOP_WORDS]
        return '_'.join(parts[:4]) if parts else "module"

    @staticmethod
    def _to_pascal(snake: str) -> str:
        """Convert snake_case to PascalCase."""
        return ''.join(word.capitalize() for word in snake.split('_') if word)

    def _gen_python(self, safe_name: str, requirements: str) -> str:
        """Generate Python module with Manager pattern."""
        cap = self._to_pascal(safe_name)
        return f'''"""
{safe_name} - Feature Module
Generated by Zenic Logic v18 (A17 CodeGenerator)
"""
from dataclasses import dataclass, field
from typing import List, Optional, Dict, Any


@dataclass
class Config:
    """Module configuration."""
    name: str = "{safe_name}"
    debug: bool = False
    max_retries: int = 3


@dataclass
class Result:
    """Operation result with error handling."""
    success: bool
    data: Any = None
    error: Optional[str] = None


class {cap}Manager:
    """Main module manager."""

    def __init__(self, config: Optional[Config] = None):
        self.config = config or Config()
        self._initialized = False

    def initialize(self) -> Result:
        """Initialize the module."""
        try:
            self._initialized = True
            return Result(success=True, data={{"status": "initialized"}})
        except Exception as e:
            return Result(success=False, error=str(e))

    def execute(self, payload: Dict[str, Any]) -> Result:
        """Execute main operation."""
        if not self._initialized:
            return Result(success=False, error="Module not initialized")
        try:
            result_data = self._process(payload)
            return Result(success=True, data=result_data)
        except Exception as e:
            return Result(success=False, error=str(e))

    def _process(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        """Internal processing - customize for your needs."""
        return {{"processed": True, "input": payload}}


if __name__ == "__main__":
    manager = {cap}Manager()
    result = manager.initialize()
    print(f"Initialization: {{result.success}}")
'''

    def _gen_kotlin(self, safe_name: str) -> str:
        """Generate Kotlin module."""
        cap = self._to_pascal(safe_name)
        return f'''// {safe_name} - Generated by Zenic Logic v18 (A17 CodeGenerator)
package com.zenic.{safe_name.lower()}

data class {cap}Config(
    val name: String = "{safe_name}",
    val debug: Boolean = false,
    val maxRetries: Int = 3
)

class {cap}Manager(private val config: {cap}Config = {cap}Config()) {{
    private var initialized = false

    fun initialize(): Result<Boolean> {{
        return try {{
            initialized = true
            Result.success(true)
        }} catch (e: Exception) {{
            Result.failure(e)
        }}
    }}

    fun execute(payload: Map<String, Any>): Result<Map<String, Any>> {{
        if (!initialized) {{
            return Result.failure(IllegalStateException("Not initialized"))
        }}
        return Result.success(mapOf("processed" to true, "input" to payload))
    }}
}}
'''

    def _gen_go(self, safe_name: str) -> str:
        """Generate Go module."""
        return f'''// {safe_name} - Generated by Zenic Logic v18 (A17 CodeGenerator)
package main

import "fmt"

type Config struct {{
        Name       string
        Debug      bool
        MaxRetries int
}}

type Manager struct {{
        config      Config
        initialized bool
}}

func NewManager(config Config) *Manager {{
        return &Manager{{config: config}}
}}

func (m *Manager) Initialize() error {{
        m.initialized = true
        return nil
}}

func (m *Manager) Execute(payload map[string]interface{{}}) (map[string]interface{{}}, error) {{
        if !m.initialized {{
                return nil, fmt.Errorf("not initialized")
        }}
        return map[string]interface{{}}{{"processed": true, "input": payload}}, nil
}}
'''

    def _gen_js(self, safe_name: str) -> str:
        """Generate JavaScript module."""
        cap = self._to_pascal(safe_name)
        return f'''// {safe_name} - Generated by Zenic Logic v18 (A17 CodeGenerator)

class {cap}Manager {{
    constructor(config = {{}}) {{
        this.config = {{
            name: "{safe_name}",
            debug: false,
            maxRetries: 3,
            ...config
        }};
        this.initialized = false;
    }}

    async initialize() {{
        this.initialized = true;
        return {{ success: true }};
    }}

    async execute(payload) {{
        if (!this.initialized) {{
            throw new Error("Not initialized");
        }}
        return {{ processed: true, input: payload }};
    }}
}}

module.exports = {{ {cap}Manager }};
'''

    def fallback(self, input_data: Any) -> CodeResult:
        """Safe fallback: empty code result."""
        return CodeResult(code="", language="python", source="fallback")
