"""
A21 ProjectScaffolder — SINGLE RESPONSIBILITY: Generate project scaffolding and boilerplate.

Deterministic project generation: file trees, configs, test templates.
No AI. Template-based multi-file project generation.
"""

from __future__ import annotations

import re
from typing import Any

from ..resilience import BaseAgent
from ..schemas import ScaffoldResult


# ──────────────────────────────────────────────────────────────
# CONSTANTS
# ──────────────────────────────────────────────────────────────

LANG_EXTENSIONS = {
    "python": ".py", "kotlin": ".kt", "go": ".go",
    "javascript": ".js", "typescript": ".ts", "java": ".java",
}

STOP_WORDS = frozenset({
    'un', 'una', 'el', 'la', 'los', 'las', 'a', 'de', 'del',
    'en', 'por', 'para', 'con', 'that', 'the', 'a', 'an',
    'create', 'make', 'generate', 'build', 'write',
})


class ProjectScaffolder(BaseAgent[ScaffoldResult]):
    """
    A21: Generate project scaffolding and boilerplate.

    Single Responsibility: Project scaffolding ONLY.
    Method: Template-based multi-file generation.
    Fallback: Empty ScaffoldResult.
    """

    def __init__(self, **kwargs) -> None:
        super().__init__(name="A21_ProjectScaffolder", **kwargs)

    def execute(self, input_data: Any) -> ScaffoldResult:
        """
        Scaffold project: generate file tree with boilerplate.

        Input (CodeRequest or dict):
            - requirements: str (project description)
            - language: str (primary language)

        Output: ScaffoldResult with files, structure, config.
        """
        if hasattr(input_data, "requirements"):
            requirements = getattr(input_data, "requirements", "")
            language = getattr(input_data, "language", "python")
        elif isinstance(input_data, dict):
            requirements = input_data.get("requirements", "")
            language = input_data.get("language", "python")
        else:
            requirements = str(input_data)
            language = "python"

        language = language.lower()
        safe_name = self._safe_name(requirements)

        if language == "python":
            files = self._scaffold_python(safe_name, requirements)
        elif language == "kotlin":
            files = self._scaffold_kotlin(safe_name)
        elif language == "go":
            files = self._scaffold_go(safe_name)
        elif language in ("javascript", "typescript"):
            files = self._scaffold_js(safe_name)
        else:
            files = self._scaffold_python(safe_name, requirements)

        structure = {safe_name: [f["path"] for f in files]}
        config = {"language": language, "name": safe_name}

        return ScaffoldResult(
            files=files,
            structure=structure,
            config=config,
            source="deterministic",
        )

    @staticmethod
    def _safe_name(text: str) -> str:
        """Convert text to safe module name."""
        name = re.sub(r'[^\w]', '_', text.lower().strip())
        name = re.sub(r'_+', '_', name).strip('_')
        parts = [p for p in name.split('_') if p and p not in STOP_WORDS]
        return '_'.join(parts[:4]) if parts else "module"

    def _scaffold_python(self, safe_name: str, requirements: str) -> list[dict[str, str]]:
        """Generate Python project structure."""
        return [
            {"path": "main.py", "content": f'''"""
{safe_name} - Main Application
Generated by Zenic Logic v18 (A21 ProjectScaffolder)
"""
from typing import Dict, Any


class App:
    """Main application class."""

    def __init__(self):
        self.name = "{safe_name}"

    def run(self) -> Dict[str, Any]:
        """Run the application."""
        return {{"status": "running", "app": self.name}}


if __name__ == "__main__":
    app = App()
    result = app.run()
    print(f"App: {{result}}")
'''},
            {"path": "requirements.txt", "content": "fastapi>=0.100.0\nuvicorn>=0.23.0\n"},
            {"path": "config.py", "content": f'''"""Configuration for {safe_name}."""

class Config:
    APP_NAME = "{safe_name}"
    DEBUG = True
    PORT = 8000
    HOST = "0.0.0.0"
'''},
            {"path": "tests/test_main.py", "content": f'''"""Tests for {safe_name}."""
from main import App


def test_app_runs():
    app = App()
    result = app.run()
    assert result["status"] == "running"
    assert result["app"] == "{safe_name}"
'''},
        ]

    def _scaffold_kotlin(self, safe_name: str) -> list[dict[str, str]]:
        """Generate Kotlin project structure."""
        cap = safe_name.capitalize()
        return [
            {"path": f"src/main/kotlin/{safe_name}/Main.kt", "content": f'''// {safe_name} - Main
package com.zenic.{safe_name}

fun main() {{
    println("{cap} application starting...")
}}
'''},
            {"path": "build.gradle.kts", "content": f'''plugins {{
    kotlin("jvm") version "1.9.20"
}}
group = "com.zenic.{safe_name}"
version = "1.0.0"
'''},
        ]

    def _scaffold_go(self, safe_name: str) -> list[dict[str, str]]:
        """Generate Go project structure."""
        return [
            {"path": "main.go", "content": f'''// {safe_name} - Main
package main

import "fmt"

func main() {{
    fmt.Println("{safe_name} application starting...")
}}
'''},
            {"path": "go.mod", "content": f"module zenic-logic.com/{safe_name}\n\ngo 1.21\n"},
        ]

    def _scaffold_js(self, safe_name: str) -> list[dict[str, str]]:
        """Generate JavaScript project structure."""
        cap = safe_name.capitalize()
        return [
            {"path": "index.js", "content": f'''// {safe_name} - Main
const {{ {cap}Manager }} = require('./lib/manager');

async function main() {{
    const manager = new {cap}Manager();
    await manager.initialize();
    const result = await manager.execute({{ action: 'start' }});
    console.log('Result:', result);
}}

main().catch(console.error);
'''},
            {"path": "package.json", "content": f'''{{
  "name": "{safe_name}",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {{
    "start": "node index.js",
    "test": "jest"
  }}
}}
'''},
        ]

    def fallback(self, input_data: Any) -> ScaffoldResult:
        """Safe fallback: empty scaffold result."""
        return ScaffoldResult(files=[], structure={}, config={}, source="fallback")
