"""
TITAN OMNISCALE X - App Android con Kivy
Motor Logico de Razonamiento Quirurgico

Todo el motor esta incluido en este archivo.
Sin dependencias externas. Compatible con Android.
"""
import hashlib
import json
import re
import os
from kivy.app import App
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.label import Label
from kivy.uix.button import Button
from kivy.uix.textinput import TextInput
from kivy.uix.scrollview import ScrollView
import threading


# ===== MOTOR TITAN OMNISCALE X =====

IS_ANDROID = 'ANDROID_ARGUMENT' in os.environ

# Constantes
OP_CREATE = "CREATE"
OP_REFACTOR = "REFACTOR"
OP_DELETE = "DELETE"
OP_SEARCH = "SEARCH"

GOAL_MODERN = "MODERN_PATTERN"
GOAL_COMPLEXITY = "COMPLEXITY_REDUCTION"
GOAL_BUGFIX = "BUG_FIX"
GOAL_FEATURE = "FEATURE_ADD"

INTENT_KEYWORDS = {
    OP_CREATE: ["create", "new", "implement", "add", "crear", "nuevo"],
    OP_REFACTOR: ["optimize", "refactor", "improve", "optimizar", "mejorar"],
    OP_DELETE: ["delete", "remove", "eliminate", "eliminar", "borrar"],
    OP_SEARCH: ["search", "find", "where", "buscar", "encontrar"],
}

GOAL_KEYWORDS = {
    GOAL_MODERN: ["modern", "update", "moderno", "actualizar"],
    GOAL_COMPLEXITY: ["reduce", "faster", "simplify", "reducir", "rapido"],
    GOAL_BUGFIX: ["fix", "correct", "bug", "error", "corregir"],
    GOAL_FEATURE: ["add", "new", "functionality", "agregar", "nueva"],
}


class TitanEngine:
    """Motor TITAN OMNISCALE X - Pure Python."""

    def __init__(self):
        self.results = {}

    def execute(self, msg):
        text = msg.lower()

        # N1 - Parse
        best_op, best_op_score = OP_SEARCH, 0
        for op, keywords in INTENT_KEYWORDS.items():
            score = sum(1 for kw in keywords if kw in text)
            if score > best_op_score:
                best_op_score, best_op = score, op

        best_goal, best_goal_score = GOAL_FEATURE, 0
        for goal, keywords in GOAL_KEYWORDS.items():
            score = sum(1 for kw in keywords if kw in text)
            if score > best_goal_score:
                best_goal_score, best_goal = score, goal

        tgt = re.search(r'([\w\.-]+(?:\.kt|\.py|\.go|\.js|\.ts))', msg)
        target = tgt.group(1) if tgt else "unknown"

        # N8 - Cache
        cache_key = hashlib.sha256(f"{best_op}|{best_goal}|{target}".encode()).hexdigest()[:12]
        if cache_key in self.results:
            return {"status": "CACHED", "code": self.results[cache_key], "hash": cache_key, "error": ""}

        # N2 - Route
        critical = any(p in target.lower() for p in ["auth", "login", "crypto", "db"])
        route = "DEEP" if critical or best_op in [OP_DELETE, OP_REFACTOR] else "FAST"

        # N5 - Generate code
        lang = "python"
        if ".kt" in target:
            lang = "kotlin"
        elif ".go" in target:
            lang = "go"

        code = self._generate(target, lang, best_op)

        # N6 - Validate
        if lang == "python":
            try:
                compile(code, target, 'exec')
                status = "SUCCESS"
            except SyntaxError as e:
                status = "ROLLBACK"
                code = ""
                error = f"Syntax error line {e.lineno}: {e.msg}"
                return {"status": status, "code": code, "hash": "N/A", "error": error}
        else:
            status = "SUCCESS" if code.strip() else "ROLLBACK"

        # N7 - Commit
        self.results[cache_key] = code

        return {"status": status, "code": code, "hash": cache_key, "error": ""}

    def _generate(self, target, lang, op):
        if lang == "python":
            return f'# TITAN OMNISCALE X - Generated for {target}\ndef main():\n    """Auto-generated by TITAN"""\n    print("Hello from {target}")\n\nif __name__ == "__main__":\n    main()\n'
        elif lang == "kotlin":
            return f'// TITAN OMNISCALE X - Generated for {target}\nfun main() {{\n    println("Hello from {target}")\n}}\n'
        elif lang == "go":
            return f'// TITAN OMNISCALE X - Generated for {target}\npackage main\n\nimport "fmt"\n\nfunc main() {{\n    fmt.Println("Hello from {target}")\n}}\n'
        return ""


# ===== INTERFAZ KIVY =====

class TitanApp(App):
    """Aplicacion TITAN OMNISCALE X."""

    def build(self):
        self.engine = TitanEngine()
        self.layout = BoxLayout(orientation='vertical', padding=20, spacing=15)

        self.title_label = Label(
            text="[b]TITAN OMNISCALE X[/b]\nMotor Logico Quirurgico",
            font_size='20sp', markup=True, size_hint=(1, 0.15)
        )

        self.input_field = TextInput(
            hint_text="Escribe tu instruccion (ej: 'optimizar auth.py')",
            multiline=False, font_size='16sp', size_hint=(1, 0.1)
        )
        self.input_field.bind(on_text_validate=self.process_command)

        self.btn = Button(
            text="EJECUTAR MOTOR",
            font_size='18sp', size_hint=(1, 0.1)
        )
        self.btn.bind(on_press=self.process_command)

        scroll = ScrollView(size_hint=(1, 0.65))
        self.output_label = Label(
            text="Motor listo. Escribe un comando para iniciar.",
            font_size='14sp', size_hint_y=None, valign='top',
        )
        self.output_label.bind(
            width=lambda *x: setattr(self.output_label, 'text_size', (self.output_label.width, None))
        )
        self.output_label.bind(texture_size=self.output_label.setter('size'))
        scroll.add_widget(self.output_label)

        self.layout.add_widget(self.title_label)
        self.layout.add_widget(self.input_field)
        self.layout.add_widget(self.btn)
        self.layout.add_widget(scroll)
        return self.layout

    def process_command(self, instance):
        msg = self.input_field.text.strip()
        if not msg:
            return
        self.output_label.text = f"Procesando: {msg}..."
        self.btn.disabled = True
        threading.Thread(target=self._run, args=(msg,), daemon=True).start()

    def _run(self, msg):
        try:
            result = self.engine.execute(msg)
            output = (
                f"TITAN OMNISCALE X\n"
                f"{'='*30}\n"
                f"Estado: {result['status']}\n"
                f"Hash: {result.get('hash', 'N/A')}\n"
                f"Error: {result.get('error', 'Ninguno')}\n"
                f"{'='*30}\n"
                f"Codigo:\n{result.get('code', '')}"
            )
        except Exception as e:
            output = f"Error: {str(e)}"

        from kivy.clock import Clock
        Clock.schedule_once(lambda dt: self._update(output))

    def _update(self, text):
        self.output_label.text = text
        self.btn.disabled = False


if __name__ == '__main__':
    TitanApp().run()
