"""
Restricted builtins and sandbox globals for safe execution.

SECURITY HARDENED (Phase 3 fixes C-01/C-02):
- Runtime interception of getattr/hasattr/setattr/delattr to block dunder access
  even when attribute name is a variable (AST-only check was bypassable)
- Removed type(), setattr, delattr from safe builtins (sandbox escape vectors)
- Wrapped type() to only allow checking existing types, not creating new ones
"""

from pathlib import Path
from typing import Any, Dict, Optional

from ._workspace import SandboxWorkspace

# Dunder names that are known sandbox escape vectors
# SECURITY: This set must be comprehensive — any dunder that provides
# access to Python internals, class hierarchy, or execution context
# can be used to escape the sandbox.
_DANGEROUS_DUNDER_NAMES = frozenset({
    # Class hierarchy and type introspection (MRO traversal -> escape)
    '__class__', '__bases__', '__subclasses__', '__mro__',
    '__base__', '__subclass_hook__',
    # Function/method internals (access to globals, closures)
    '__globals__', '__code__', '__closure__', '__func__',
    '__self__', '__dict__', '__weakref__',
    '__builtins__', '__import__',
    # Object lifecycle — can create objects with arbitrary behavior
    '__call__', '__new__', '__init__', '__del__',
    # Attribute access interception — can bypass security checks
    '__getattr__', '__getattribute__', '__setattr__', '__delattr__',
    # Context manager — can execute code on entry/exit
    '__enter__', '__exit__',
    # Descriptor protocol — can intercept attribute access
    '__get__', '__set__', '__delete__',
    # Serialization — can reconstruct objects from pickled data
    '__reduce__', '__reduce_ex__', '__getstate__',
    '__setstate__',
    # Metaclass and class creation
    '__init_subclass__', '__class_getitem__',
    # Async — can trigger code execution
    '__await__',
    # Note: __iter__, __next__, __eq__, __hash__, __str__, __repr__, __format__
    # are NOT dangerous — they are listed in _SAFE_DUNDER_NAMES below.
})

# Allowlist of safe dunders that don't enable sandbox escape.
# Checked BEFORE the dangerous list in _is_dangerous_attr().
# Module-level constant to avoid recreating the frozenset on every call.
_SAFE_DUNDER_NAMES = frozenset({
    '__name__', '__doc__', '__module__', '__annotations__',
    '__len__', '__getitem__', '__setitem__', '__delitem__',
    '__contains__', '__iter__', '__next__',  # iteration is safe in builtins
    '__add__', '__radd__', '__sub__', '__rsub__',
    '__mul__', '__rmul__', '__truediv__', '__floordiv__',
    '__mod__', '__pow__', '__matmul__',
    '__and__', '__or__', '__xor__',
    '__eq__', '__ne__', '__lt__', '__le__', '__gt__', '__ge__',
    '__hash__', '__bool__', '__int__', '__float__', '__str__',
    '__repr__', '__format__',
    '__abs__', '__neg__', '__pos__', '__invert__',
    '__round__', '__trunc__', '__floor__', '__ceil__',
})

# Modules that are safe to import inside the sandbox.
# Module-level constant to avoid recreating the set on every call.
_SAFE_MODULES = frozenset({
    'math', 'random', 'string', 'collections', 'itertools',
    'functools', 'operator', 'typing', 'enum', 'dataclasses',
    'abc', 'copy', 're', 'json', 'decimal', 'fractions',
    'statistics', 'datetime', 'time', 'hashlib', 'base64',
    'struct', 'pprint', 'textwrap',
    'collections.abc',
    'inspect',   # Needed by generated code's _validate_not_none() — safe in sandbox context
    'hmac',      # Security/authorization code generated by the pipeline
    'secrets',   # Token generation code generated by the pipeline
    'os.path',   # Path manipulation (read-only, no os.system)
})


def _is_dangerous_attr(name: str) -> bool:
    """Check if an attribute name is a dangerous dunder that enables sandbox escape.

    Security: Blocks ALL dunder attributes (starts and ends with __) except
    a small allowlist of harmless ones like __name__, __doc__, __module__,
    __annotations__, __len__, __getitem__, __setitem__, __contains__,
    __add__, __mul__, and other operator dunders that are safe.
    """
    if isinstance(name, str) and name.startswith('__') and name.endswith('__'):
        if name in _SAFE_DUNDER_NAMES:
            return False
        # Any dunder not in the allowlist is considered dangerous
        return True
    return False


def create_sandbox_builtins(workspace: SandboxWorkspace) -> dict:
    """
    Crea un diccionario de builtins restringidos para ejecucion en sandbox.

    Garantias de seguridad:
    - NO hay acceso a os.system, subprocess, eval, exec, __import__
    - open() solo puede escribir/leer DENTRO del workspace
    - NO hay acceso al filesystem fuera del workspace
    - Las operaciones de archivo se redirigen al workspace aislado
    - Runtime interception blocks dunder access via getattr/hasattr with variables
    - type() is wrapped to prevent subclass-based sandbox escape
    - setattr/delattr are wrapped to reject dunder attributes
    """
    # open() restringido que solo opera dentro del workspace
    def _sandbox_open(filepath, mode='r', *args, **kwargs):
        """open() restringido: solo permite acceso dentro del workspace.

        Security: TOCTOU mitigation — validates path AND opens in one step
        using the resolved path, minimizing the window for symlink attacks.
        """
        # Resolver la ruta absoluta
        path = Path(filepath)

        # Si es relativa, resolverla contra el workspace
        if not path.is_absolute():
            path = workspace.projects_dir / filepath

        # Verificar que la ruta resolve esta DENTRO del workspace
        # SECURITY: Resolve the path immediately and use it for the open() call
        # to minimize the TOCTOU window between validation and file access.
        try:
            resolved = path.resolve()
            workspace_resolved = workspace.workspace_dir.resolve()
            if not resolved.is_relative_to(workspace_resolved):
                raise PermissionError(
                    f"Sandbox: acceso denegado a '{filepath}'. "
                    f"Solo se permite acceso dentro del workspace aislado."
                )
        except (OSError, ValueError):
            raise PermissionError(
                f"Sandbox: ruta invalida '{filepath}'."
            )

        # Si es escritura, asegurar que el directorio existe
        if 'w' in mode or 'a' in mode:
            resolved.parent.mkdir(parents=True, exist_ok=True)

        # SECURITY: Open the RESOLVED path directly (not the original path)
        # This closes the TOCTOU window — no re-resolution between check and use.
        # For read modes, also verify the opened file still resolves correctly
        # (protection against symlink replacement after validation).
        try:
            f = open(resolved, mode, *args, **kwargs)
        except FileNotFoundError:
            raise
        except PermissionError:
            raise
        except Exception as e:
            raise OSError(f"Sandbox: error opening file '{filepath}': {e}") from e

        # Post-open validation for read modes: verify the actual file descriptor
        # still points within the workspace (mitigates symlink races)
        if 'r' in mode:
            try:
                fd_path = Path(f"/proc/self/fd/{f.fileno()}")
                if fd_path.exists():
                    real_path = fd_path.resolve()
                    if not real_path.is_relative_to(workspace_resolved):
                        f.close()
                        raise PermissionError(
                            f"Sandbox: file descriptor escape detected for '{filepath}'"
                        )
            except (OSError, ValueError):
                pass  # /proc not available on all platforms (Android, Windows)

        return f

    # __import__ restringido: solo permite modulos seguros
    def _sandbox_import(name, *args, **kwargs):
        """__import__ restringido: solo modulos seguros permitidos."""
        base_name = name.split('.')[0]
        if base_name not in _SAFE_MODULES:
            raise ImportError(
                f"Sandbox: importacion de '{name}' bloqueada. "
                f"Solo se permiten modulos seguros: {sorted(_SAFE_MODULES)}"
            )
        return __import__(name, *args, **kwargs)

    # SECURITY (C-01): Runtime interception of getattr/hasattr
    # AST validation only catches literal strings; a variable holding a dunder
    # name bypasses AST checks. This runtime guard blocks ALL dunder access.
    _original_getattr = getattr
    _original_hasattr = hasattr

    def _sandbox_getattr(obj, name, *default):
        """getattr() restringido: bloquea acceso a dunder names en runtime."""
        if _is_dangerous_attr(name):
            raise AttributeError(
                f"Sandbox: access to attribute '{name}' is blocked for security"
            )
        if default:
            return _original_getattr(obj, name, default[0])
        return _original_getattr(obj, name)

    def _sandbox_hasattr(obj, name):
        """hasattr() restringido: bloquea acceso a dunder names en runtime."""
        if _is_dangerous_attr(name):
            raise AttributeError(
                f"Sandbox: access to attribute '{name}' is blocked for security"
            )
        return _original_hasattr(obj, name)

    # SECURITY (C-02): Wrap setattr/delattr to reject dunder injection
    _original_setattr = setattr
    _original_delattr = delattr

    def _sandbox_setattr(obj, name, value):
        """setattr() restringido: bloquea inyeccion de dunder attributes."""
        if _is_dangerous_attr(name):
            raise AttributeError(
                f"Sandbox: setting attribute '{name}' is blocked for security"
            )
        _original_setattr(obj, name, value)

    def _sandbox_delattr(obj, name):
        """delattr() restringido: bloquea eliminacion de dunder attributes."""
        if _is_dangerous_attr(name):
            raise AttributeError(
                f"Sandbox: deleting attribute '{name}' is blocked for security"
            )
        _original_delattr(obj, name)

    # SECURITY (C-02): Wrap type() to prevent subclass-based sandbox escape.
    # type() with 3 args creates new classes with __init_subclass__ hooks,
    # descriptors, and metaclasses that can access __globals__ and escape.
    # We only allow type() with 1 arg (type(obj) -> returns the type) or
    # 3 args where the class body is a plain dict (no exec'd body).
    _original_type = type

    def _sandbox_type(*args):
        """type() restringido: solo permite introspeccion, no creacion de clases."""
        if len(args) == 1:
            # type(obj) -> safe, just returns the type of the object
            return _original_type(args[0])
        if len(args) == 3:
            name, bases, namespace = args
            # Block class creation with metaclasses or non-dict namespaces
            if not isinstance(namespace, dict):
                raise TypeError(
                    "Sandbox: type() class creation with non-dict namespace is blocked"
                )
            # Block classes with dangerous dunder methods in the namespace
            for key in namespace:
                if _is_dangerous_attr(key):
                    raise TypeError(
                        f"Sandbox: type() class creation with '{key}' "
                        f"in namespace is blocked for security"
                    )
            # Block bases that include metaclasses (not plain object inheritance)
            for base in (bases if isinstance(bases, tuple) else (bases,)):
                base_type = _original_type(base)
                if base_type is not type and base_type is not object:
                    raise TypeError(
                        "Sandbox: type() with metaclass bases is blocked for security"
                    )
            return _original_type(name, bases, namespace)
        raise TypeError(
            f"Sandbox: type() with {len(args)} arguments is not supported"
        )

    # Construir diccionario de builtins
    safe_builtins = {
        # I/O restringido
        'open': _sandbox_open,
        'print': lambda *a, **kw: None,  # Mocked: no side effects

        # Tipos basicos — type() wrapped for security (C-02)
        'bool': bool, 'int': int, 'float': float, 'str': str,
        'list': list, 'dict': dict, 'set': set, 'tuple': tuple,
        'bytes': bytes, 'bytearray': bytearray, 'frozenset': frozenset,
        'complex': complex, 'range': range, 'type': _sandbox_type,
        'slice': slice, 'object': object, 'memoryview': memoryview,

        # Funciones builtins seguras — getattr/hasattr/setattr/delattr wrapped (C-01/C-02)
        'len': len, 'abs': abs, 'min': min, 'max': max, 'sum': sum,
        'round': round, 'pow': pow, 'divmod': divmod,
        'sorted': sorted, 'reversed': reversed, 'enumerate': enumerate,
        'zip': zip, 'map': map, 'filter': filter, 'all': all, 'any': any,
        'chr': chr, 'ord': ord, 'hex': hex, 'oct': oct, 'bin': bin,
        'format': format, 'repr': repr, 'ascii': ascii,
        'isinstance': isinstance, 'issubclass': issubclass,
        'hasattr': _sandbox_hasattr, 'getattr': _sandbox_getattr,
        'setattr': _sandbox_setattr, 'delattr': _sandbox_delattr,
        'dir': lambda *a, **kw: [],  # Blocked: exposes dunder attributes for sandbox escape
        'vars': lambda *a, **kw: {},  # Blocked: exposes __dict__ for sandbox escape
        'super': super,  # Allowed: needed for class inheritance in generated code (e.g. super().__init__())
        'callable': callable, 'hash': hash, 'id': id,
        'property': property, 'classmethod': classmethod,
        'staticmethod': staticmethod,

        # Excepciones permitidas
        'Exception': Exception, 'ValueError': ValueError,
        'TypeError': TypeError, 'KeyError': KeyError,
        'AttributeError': AttributeError, 'IndexError': IndexError,
        'RuntimeError': RuntimeError, 'StopIteration': StopIteration,
        'NotImplementedError': NotImplementedError,
        'ZeroDivisionError': ZeroDivisionError,
        'OverflowError': OverflowError,
        'AssertionError': AssertionError,
        'LookupError': LookupError, 'IOError': IOError,
        'OSError': OSError, 'FileNotFoundError': FileNotFoundError,
        'PermissionError': PermissionError,
        'ArithmeticError': ArithmeticError,
        'BufferError': BufferError,

        # Constantes
        'True': True, 'False': False, 'None': None,
        'NotImplemented': NotImplemented, 'Ellipsis': Ellipsis,

        # Importacion restringida
        '__import__': _sandbox_import,

        # SECURITY: Explicitly block dangerous builtins even if referenced
        'eval': lambda *a, **kw: (_ for _ in ()).throw(
            ImportError("Sandbox: eval() is blocked for security")),
        'exec': lambda *a, **kw: (_ for _ in ()).throw(
            ImportError("Sandbox: exec() is blocked for security")),
        'compile': lambda *a, **kw: (_ for _ in ()).throw(
            ImportError("Sandbox: compile() is blocked for security")),
        'breakpoint': lambda *a, **kw: (_ for _ in ()).throw(
            ImportError("Sandbox: breakpoint() is blocked for security")),
        'input': lambda *a, **kw: (_ for _ in ()).throw(
            ImportError("Sandbox: input() is blocked for security")),
        'exit': lambda *a, **kw: (_ for _ in ()).throw(
            ImportError("Sandbox: exit() is blocked for security")),
        'quit': lambda *a, **kw: (_ for _ in ()).throw(
            ImportError("Sandbox: quit() is blocked for security")),
        'globals': lambda *a, **kw: {},
        'locals': lambda *a, **kw: {},
    }

    return safe_builtins


def create_sandbox_globals(workspace: SandboxWorkspace,
                           extra_globals: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    """
    Crea el diccionario de globals para ejecucion segura en sandbox.

    Args:
        workspace: Workspace aislado donde se ejecuta el codigo.
        extra_globals: Variables adicionales a inyectar.

    Returns:
        Dict listo para usar como segundo argumento de exec().
    """
    safe_builtins = create_sandbox_builtins(workspace)

    sandbox_globals = {
        "__builtins__": safe_builtins,
        "__name__": "__sandbox__",
        "__file__": str(workspace.code_dir / "sandbox_code.py"),
        "__doc__": None,
    }

    # Agregar globals extra si se proporcionan
    if extra_globals:
        # Filtrar globals peligrosas
        dangerous_keys = {
            'os', 'sys', 'subprocess', 'shutil', 'signal',
            'socket', 'http', 'urllib', 'requests',
            'ctypes', 'multiprocessing', 'threading',
            'pickle', 'shelve', 'marshal',
        }
        for key, value in extra_globals.items():
            if key not in dangerous_keys:
                sandbox_globals[key] = value

    return sandbox_globals
