"""
CodeAgent Fallbacks — deterministic fallback generators + refactor/optimize/fix
methods as mixin.

Extracted from the monolithic code_agent.py (1,043 lines) as part of the
mixin-based modularisation.  Contains task-specific fallback methods and
Python-specific deterministic transformers.
"""

import ast
import re
from typing import Any, Dict

from src.core.agents.schemas import CodeOutput, FileSpec
from src.core.agents.code_agent_parts.helpers import LANG_EXTENSIONS


class CodeAgentFallbacksMixin:
    """Mixin with fallback generators and transformers for CodeAgent."""

    # ============================================================
    #  FALLBACK GENERATORS (deterministic code generation)
    # ============================================================

    def _fallback_generate(self, requirements: str, language: str,
                           constraints: Dict[str, Any]) -> CodeOutput:
        """Generación determinista de código nuevo."""
        safe_name = self._safe_name(requirements)

        if language == "python":
            return self._gen_python_module(safe_name, requirements)
        elif language == "kotlin":
            return self._gen_kotlin_module(safe_name)
        elif language == "go":
            return self._gen_go_module(safe_name)
        elif language == "javascript":
            return self._gen_js_module(safe_name)
        return self._gen_python_module(safe_name, requirements)

    def _fallback_transform(self, existing_code: str, requirements: str,
                             language: str) -> CodeOutput:
        """Transformación determinista de código existente (refactor)."""
        if not existing_code:
            return CodeOutput(
                code="# No existing code provided for transformation\n",
                language=language,
                explanation="Cannot transform empty code. Provide existing code.",
            )

        if language == "python":
            return self._refactor_python(existing_code, requirements)
        # For non-Python, return code as-is with explanation
        return CodeOutput(
            code=existing_code,
            language=language,
            explanation=f"Transformation requested: {requirements[:200]}. "
                        f"LLM required for non-Python transformations.",
        )

    def _fallback_optimize(self, existing_code: str,
                           language: str) -> CodeOutput:
        """Optimización determinista de código existente."""
        if not existing_code:
            return CodeOutput(
                code="# No existing code provided for optimization\n",
                language=language,
                explanation="Cannot optimize empty code.",
            )

        if language == "python":
            return self._optimize_python(existing_code)
        return CodeOutput(
            code=existing_code,
            language=language,
            explanation="Optimization requires LLM for non-Python code.",
        )

    def _fallback_fix(self, existing_code: str, language: str) -> CodeOutput:
        """Corrección determinista de código existente."""
        if not existing_code:
            return CodeOutput(
                code="# No existing code provided for fixing\n",
                language=language,
                explanation="Cannot fix empty code.",
            )

        if language == "python":
            return self._fix_python(existing_code)
        return CodeOutput(
            code=existing_code,
            language=language,
            explanation="Bug fixing requires LLM for non-Python code.",
        )

    def _fallback_scaffold(self, requirements: str,
                           language: str) -> CodeOutput:
        """Scaffolding determinista de proyecto."""
        safe_name = self._safe_name(requirements)

        if language == "python":
            files = self._scaffold_python_project(safe_name, requirements)
        else:
            files = [FileSpec(
                path=f"main{LANG_EXTENSIONS.get(language, '.txt')}",
                content=f"// {safe_name} - Generated by TITAN OMNISCALE X\n",
                language=language,
            )]

        return CodeOutput(
            code=files[0].content if files else "",
            language=language,
            files=files,
            explanation=f"Scaffolded {safe_name} project with {len(files)} files",
        )

    # ============================================================
    #  PYTHON TRANSFORMERS (deterministic)
    # ============================================================

    def _refactor_python(self, code: str, requirements: str) -> CodeOutput:
        """Refactorización determinista de Python (preserves CodeTransformer contract)."""
        try:
            tree = ast.parse(code)
        except SyntaxError:
            return CodeOutput(code=code, language="python",
                              explanation="Cannot parse code - returning original")

        refactor_notes = []
        lines = code.split('\n')
        modified_lines = list(lines)

        for node in ast.walk(tree):
            if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                continue

            func_name = node.name
            func_start = node.lineno - 1
            args = [a.arg for a in node.args.args]
            has_return_annotation = node.returns is not None

            # Calculate complexity
            complexity = sum(1 for n in ast.walk(node)
                           if isinstance(n, (ast.If, ast.While, ast.For, ast.ExceptHandler)))

            # Add return type annotation if missing
            if not has_return_annotation and args:
                sig_line = func_start
                if 0 <= sig_line < len(modified_lines):
                    line = modified_lines[sig_line]
                    if '-> ' not in line and line.rstrip().endswith(':'):
                        modified_lines[sig_line] = line.rstrip()[:-1] + ' -> Any:'
                        refactor_notes.append(f"Added return type annotation to '{func_name}'")

            if complexity > 10:
                refactor_notes.append(
                    f"'{func_name}' complexity={complexity} - consider extracting helpers"
                )

        result = '\n'.join(modified_lines)
        if refactor_notes:
            result += "\n\n# TITAN OMNISCALE X Refactoring Notes:\n" + "\n".join(
                f"# - {n}" for n in refactor_notes
            )

        return CodeOutput(code=result, language="python",
                          explanation=f"Refactored with {len(refactor_notes)} improvements")

    def _optimize_python(self, code: str) -> CodeOutput:
        """Optimización determinista de Python."""
        try:
            tree = ast.parse(code)
        except SyntaxError:
            return CodeOutput(code=code, language="python",
                              explanation="Cannot parse code - returning original")

        optimizations = []

        # Check for bare except
        for node in ast.walk(tree):
            if isinstance(node, ast.ExceptHandler) and node.type is None:
                optimizations.append("Bare 'except:' found - replace with 'except Exception:'")

        # Check for open() without with
        for node in ast.walk(tree):
            if isinstance(node, ast.Call):
                func = getattr(node, 'func', None)
                if isinstance(func, ast.Name) and func.id == 'open':
                    optimizations.append("open() without 'with' - potential resource leak")

        if optimizations:
            notes = "\n".join(f"# - {o}" for o in optimizations)
            return CodeOutput(
                code=code + f"\n\n# TITAN OMNISCALE X Optimization Notes:\n{notes}",
                language="python",
                explanation=f"Found {len(optimizations)} optimization opportunities",
            )

        return CodeOutput(code=code, language="python",
                          explanation="No obvious optimizations found")

    def _fix_python(self, code: str) -> CodeOutput:
        """Corrección determinista de Python (preserves CodeTransformer.fix_python contract)."""
        fixes = []
        lines = code.split('\n')
        fixed_lines = list(lines)

        for i, line in enumerate(lines):
            # Fix missing colons
            if re.match(r'^\s*(def|if|elif|else|for|while|try|except|finally|with|class)\s', line):
                if not line.rstrip().endswith(':') and not line.rstrip().endswith('\\'):
                    fixed_lines[i] = line.rstrip() + ':'
                    fixes.append(f"Line {i+1}: Added missing ':'")

        # Fix bare except
        for i, line in enumerate(lines):
            if 'except:' in line and 'except Exception:' not in line:
                fixed_lines[i] = line.replace('except:', 'except Exception:')
                fixes.append(f"Line {i+1}: Changed bare 'except:' to 'except Exception:'")

        result = '\n'.join(fixed_lines)
        if fixes:
            result += "\n\n# TITAN OMNISCALE X Fixes:\n" + "\n".join(f"# - {f}" for f in fixes)
        else:
            result += "\n\n# TITAN OMNISCALE X: No obvious bugs found."

        return CodeOutput(code=result, language="python",
                          explanation=f"Applied {len(fixes)} fixes")
