"""
TITAN OMNISCALE X - FractalGenerator v16

Data structures for fractal generation.
"""

import logging
from typing import Dict, Any, List, Optional
from dataclasses import dataclass, field

logger = logging.getLogger(__name__)


# ============================================================
#  DATA STRUCTURES - Especificaciones de la generación fractal
# ============================================================

@dataclass
class FileBlueprint:
    """Blueprint de un archivo individual en el proyecto."""
    path: str = ""                     # Ruta relativa (ej: "src/models.py")
    language: str = "python"           # Lenguaje del archivo
    description: str = ""              # Descripción breve del propósito
    classes: List[Dict[str, str]] = field(default_factory=list)
        # [{"name": "User", "docstring": "Modelo de usuario", "bases": "Base"}]
    functions: List[Dict[str, str]] = field(default_factory=list)
        # [{"name": "create_user", "docstring": "Crea un usuario", "params": "data: dict"}]
    imports: List[str] = field(default_factory=list)
        # ["from sqlalchemy import Column, Integer, String"]
    generated_content: str = ""         # Content generated by FractalGenerator phases


@dataclass
class FractalSpec:
    """Especificación completa del proyecto a generar."""
    project_name: str = ""
    project_type: str = ""             # auth_system, crud_dashboard, etc.
    language: str = "python"
    description: str = ""
    directories: List[str] = field(default_factory=list)
        # ["src/", "src/models/", "src/routes/", "tests/"]
    files: List[FileBlueprint] = field(default_factory=list)
    config_files: Dict[str, str] = field(default_factory=dict)
        # {"requirements.txt": "flask\nsqlalchemy", ".env": "SECRET=xxx"}
    phase: int = 0                     # 1=structural, 2=skeletons, 3=filled
    current_file_index: int = 0        # Archivo actual en procesamiento
    current_item_index: int = 0        # Item actual dentro del archivo


@dataclass
class FractalResult:
    """Resultado de la generación fractal."""
    status: str = "pending"            # pending|structural|skeletons|filled|complete
    project_name: str = ""
    spec: Optional[FractalSpec] = None
    files_generated: List[str] = field(default_factory=list)
    total_files: int = 0
    current_phase: int = 0
    items_completed: int = 0
    items_total: int = 0
    error: str = ""
