"""
TITAN OMNISCALE X - File Generator Mixin

Methods that generate simpler Python code files:
_gen_requirements, _gen_database, _gen_models, _gen_config
"""

import re
import secrets


class FileGeneratorMixin:
    """Mixin with core file generation methods for AppGenerator."""

    def _gen_requirements(self, plan) -> str:
        """Genera requirements.txt."""
        base = [
            "fastapi>=0.100.0",
            "uvicorn>=0.23.0",
            "jinja2>=3.1.0",
            "python-multipart>=0.0.6",
        ]

        # Add based on template
        if plan.template_type in ["invoice_billing", "report_generator"]:
            base.append("weasyprint>=59.0")
        if plan.template_type in ["email_automation", "email_sender", "notification_service"]:
            base.append("aiosmtplib>=3.0.0")
        if plan.template_type in ["scheduler", "scheduled_report"]:
            base.append("apscheduler>=3.10.0")
        if plan.template_type in ["data_pipeline", "data_sync"]:
            base.append("aiohttp>=3.8.0")

        return "\n".join(base) + "\n"

    def _gen_database(self, plan, project_name: str) -> str:
        """Genera database.py - Configuración SQLite con init automático."""
        entities = plan.entities
        table_creates = []
        for entity in entities:
            name = entity.get("name", "Item")
            fields = entity.get("fields", [])
            # Validate entity name — only alphanumeric + underscore allowed
            if not re.match(r'^[a-zA-Z_]\w*$', name.lower()):
                raise ValueError(f"Invalid entity name: {name}. Only alphanumeric characters and underscores allowed.")
            columns = ["id INTEGER PRIMARY KEY AUTOINCREMENT"]
            for f in fields:
                parts = f.split(":")
                fname = parts[0]
                ftype = parts[1] if len(parts) > 1 else "str"
                sql_type = {"int": "INTEGER", "float": "REAL", "bool": "INTEGER",
                            "str": "TEXT", "datetime": "TEXT", "list": "TEXT",
                            "dict": "TEXT"}.get(ftype, "TEXT")
                columns.append(f"{fname} {sql_type}")
            table_creates.append(
                f'CREATE TABLE IF NOT EXISTS {name.lower()} (\n'
                + ",\n".join(f"        {c}" for c in columns)
                + "\n    )"
            )

        tables_sql = "\n\n    ".join(table_creates) if table_creates else "CREATE TABLE IF NOT EXISTS item (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, created_at TEXT)"

        return f'''"""
{project_name} - Database Configuration
Auto-generated by TITAN OMNISCALE X
"""
import sqlite3
import os
from typing import List, Dict, Any, Optional

DB_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "data")
DB_PATH = os.path.join(DB_DIR, "{plan.config_vars.get('db_name', project_name + '.db')}")

def get_connection() -> sqlite3.Connection:
    """Obtiene conexión a la base de datos SQLite."""
    os.makedirs(DB_DIR, exist_ok=True)
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA foreign_keys=ON")
    return conn

def init_db():
    """Inicializa la base de datos con las tablas necesarias."""
    conn = get_connection()
    try:
        conn.executescript("""
    {tables_sql}
    """)
        conn.commit()
    finally:
        conn.close()

def execute_query(sql: str, params: tuple = ()) -> List[Dict[str, Any]]:
    """Ejecuta una query SELECT y devuelve resultados como lista de dicts."""
    conn = get_connection()
    try:
        cursor = conn.execute(sql, params)
        rows = cursor.fetchall()
        return [dict(row) for row in rows]
    finally:
        conn.close()

def execute_insert(sql: str, params: tuple = ()) -> int:
    """Ejecuta INSERT/UPDATE/DELETE y devuelve el lastrowid."""
    conn = get_connection()
    try:
        cursor = conn.execute(sql, params)
        conn.commit()
        return cursor.lastrowid
    finally:
        conn.close()

def execute_update(sql: str, params: tuple = ()) -> int:
    """Ejecuta UPDATE/DELETE y devuelve filas afectadas."""
    conn = get_connection()
    try:
        cursor = conn.execute(sql, params)
        conn.commit()
        return cursor.rowcount
    finally:
        conn.close()

# Inicializar DB al importar
init_db()
'''

    def _gen_models(self, plan, project_name: str) -> str:
        """Genera models.py - Modelos de datos con dataclasses."""
        entities = plan.entities
        model_classes = []

        for entity in entities:
            name = entity.get("name", "Item")
            fields = entity.get("fields", [])

            field_defs = ["    id: Optional[int] = None"]
            for f in fields:
                parts = f.split(":")
                fname = parts[0]
                ftype = parts[1] if len(parts) > 1 else "str"
                py_type = {"int": "int", "float": "float", "bool": "bool",
                           "str": "str", "datetime": "str", "list": "str",
                           "dict": "str"}.get(ftype, "str")
                default = 'None' if py_type in ("int", "float") else '""' if py_type == "str" else "None"
                field_defs.append(f"    {fname}: Optional[{py_type}] = {default}")

            fields_str = "\n".join(field_defs)
            model_classes.append(f'''@dataclass
class {name}:
    """Modelo de datos para {name}."""
{fields_str}

    def to_dict(self) -> Dict[str, Any]:
        return {{k: v for k, v in asdict(self).items() if v is not None}}

    @classmethod
    def from_row(cls, row: Dict[str, Any]) -> "{name}":
        return cls(**{{k: v for k, v in row.items() if k in cls.__dataclass_fields__}})''')

        models_str = "\n\n\n".join(model_classes) if model_classes else '''@dataclass
class Item:
    """Modelo genérico."""
    id: Optional[int] = None
    name: str = ""
    description: str = ""
    created_at: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        return {k: v for k, v in asdict(self).items() if v is not None}'''

        return f'''"""
{project_name} - Data Models
Auto-generated by TITAN OMNISCALE X
"""
from dataclasses import dataclass, asdict, field
from typing import Optional, List, Dict, Any
from datetime import datetime

{models_str}
'''

    def _gen_config(self, plan, project_name: str) -> str:
        """Genera config.py."""
        return f'''"""
{project_name} - Configuration
Auto-generated by TITAN OMNISCALE X
"""
import os

class Config:
    """Application configuration."""
    APP_NAME = "{project_name}"
    APP_TYPE = "{plan.template_type}"
    DEBUG = True
    PORT = {plan.config_vars.get('port', 8000)}
    HOST = "0.0.0.0"
    SECRET_KEY = "{plan.config_vars.get('secret_key', secrets.token_hex(32))}"
    DATABASE_NAME = "{plan.config_vars.get('db_name', project_name + '.db')}"

    # Pagination
    ITEMS_PER_PAGE = 20

    # Dates
    DATE_FORMAT = "%Y-%m-%d"
    DATETIME_FORMAT = "%Y-%m-%d %H:%M:%S"


class ProductionConfig(Config):
    """Production configuration."""
    DEBUG = False
    SECRET_KEY = os.environ.get("SECRET_KEY", Config.SECRET_KEY)
'''
