"""
TITAN OMNISCALE X - Service Generator Mixin

Methods that generate service and main application code files:
_gen_services, _gen_stats_methods, _gen_main
"""


class ServiceGeneratorMixin:
    """Mixin with service/main generation methods for AppGenerator."""

    def _gen_services(self, plan, project_name: str) -> str:
        """Genera services.py - Lógica de negocio."""
        entities = plan.entities
        service_methods = []

        for entity in entities:
            name = entity.get("name", "Item")
            name_lower = name.lower()
            fields = entity.get("fields", [])

            # Build field params for create
            create_params = []
            insert_cols = ["id"]
            insert_vals = ["NULL"]
            for f in fields:
                parts = f.split(":")
                fname = parts[0]
                create_params.append(fname)
                insert_cols.append(fname)
                insert_vals.append(f"?")

            params_str = ", ".join(create_params)
            cols_str = ", ".join(insert_cols)
            vals_str = ", ".join(insert_vals)
            param_tuple = ", ".join(create_params)

            update_sets = []
            for f in fields:
                parts = f.split(":")
                fname = parts[0]
                update_sets.append(f"{fname} = ?")
            update_sets.append("id = id")
            update_str = ", ".join(update_sets[:len(fields)])
            update_params = ", ".join(create_params) + ", item_id"

            service_methods.append(f'''
    # === {name} CRUD ===

    @staticmethod
    def list_{name_lower}s(search: str = "", page: int = 1, per_page: int = 20) -> List[Dict]:
        """Lista todos los {name_lower}s con búsqueda opcional."""
        offset = (page - 1) * per_page
        if search:
            return execute_query(
                "SELECT * FROM {name_lower} WHERE name LIKE ? ORDER BY id DESC LIMIT ? OFFSET ?",
                (f"%{{search}}%", per_page, offset)
            )
        return execute_query(
            "SELECT * FROM {name_lower} ORDER BY id DESC LIMIT ? OFFSET ?",
            (per_page, offset)
        )

    @staticmethod
    def get_{name_lower}(item_id: int) -> Optional[Dict]:
        """Obtiene un {name_lower} por ID."""
        results = execute_query("SELECT * FROM {name_lower} WHERE id = ?", (item_id,))
        return results[0] if results else None

    @staticmethod
    def create_{name_lower}({params_str}) -> int:
        """Crea un nuevo {name_lower}."""
        now = datetime.now().isoformat()
        return execute_insert(
            "INSERT INTO {name_lower} ({cols_str}) VALUES ({vals_str})",
            ({param_tuple},)
        )

    @staticmethod
    def update_{name_lower}(item_id: int, {params_str}) -> int:
        """Actualiza un {name_lower} existente."""
        return execute_update(
            "UPDATE {name_lower} SET {update_str} WHERE id = ?",
            ({update_params},)
        )

    @staticmethod
    def delete_{name_lower}(item_id: int) -> int:
        """Elimina un {name_lower}."""
        return execute_update("DELETE FROM {name_lower} WHERE id = ?", (item_id,))

    @staticmethod
    def count_{name_lower}s(search: str = "") -> int:
        """Cuenta el total de {name_lower}s."""
        if search:
            result = execute_query("SELECT COUNT(*) as cnt FROM {name_lower} WHERE name LIKE ?", (f"%{{search}}%",))
        else:
            result = execute_query("SELECT COUNT(*) as cnt FROM {name_lower}")
        return result[0]["cnt"] if result else 0''')

        services_str = "\n".join(service_methods) if service_methods else '''
    # === Generic Item CRUD ===

    @staticmethod
    def list_items(search: str = "", page: int = 1, per_page: int = 20) -> List[Dict]:
        offset = (page - 1) * per_page
        if search:
            return execute_query("SELECT * FROM item WHERE name LIKE ? ORDER BY id DESC LIMIT ? OFFSET ?",
                                 (f"%{search}%", per_page, offset))
        return execute_query("SELECT * FROM item ORDER BY id DESC LIMIT ? OFFSET ?", (per_page, offset))

    @staticmethod
    def get_item(item_id: int) -> Optional[Dict]:
        results = execute_query("SELECT * FROM item WHERE id = ?", (item_id,))
        return results[0] if results else None

    @staticmethod
    def create_item(name: str, description: str = "") -> int:
        now = datetime.now().isoformat()
        return execute_insert("INSERT INTO item (id, name, description, created_at) VALUES (NULL, ?, ?, ?)",
                              (name, description, now))

    @staticmethod
    def delete_item(item_id: int) -> int:
        return execute_update("DELETE FROM item WHERE id = ?", (item_id,))'''

        # Add dashboard stats method
        stats_methods = self._gen_stats_methods(plan)

        return f'''"""
{project_name} - Business Services
Auto-generated by TITAN OMNISCALE X
"""
from datetime import datetime
from typing import List, Dict, Any, Optional

from database import execute_query, execute_insert, execute_update


class Service:
    """Capa de servicios - Lógica de negocio."""
{services_str}

{stats_methods}
'''

    def _gen_stats_methods(self, plan) -> str:
        """Genera métodos de estadísticas para el dashboard."""
        stats = []
        for entity in plan.entities[:3]:
            name = entity.get("name", "Item")
            name_lower = name.lower()
            stats.append(f'''
    @staticmethod
    def get_{name_lower}_stats() -> Dict[str, Any]:
        """Obtiene estadísticas de {name_lower}s."""
        total = execute_query("SELECT COUNT(*) as cnt FROM {name_lower}")
        recent = execute_query("SELECT * FROM {name_lower} ORDER BY id DESC LIMIT 5")
        return {{
            "total": total[0]["cnt"] if total else 0,
            "recent": recent,
        }}''')

        return "\n".join(stats) if stats else '''
    @staticmethod
    def get_dashboard_stats() -> Dict[str, Any]:
        """Obtiene estadísticas generales del dashboard."""
        return {"total": 0, "recent": []}'''

    def _gen_main(self, plan, project_name: str) -> str:
        """Genera main.py - Aplicación FastAPI completa."""
        entities = plan.entities
        endpoints = plan.endpoints

        # Generate API routes
        api_routes = []
        for entity in entities:
            name = entity.get("name", "Item")
            name_lower = name.lower()
            fields = entity.get("fields", [])
            create_params = ["name: str"]
            for f in fields[1:]:
                parts = f.split(":")
                fname = parts[0]
                ftype = parts[1] if len(parts) > 1 else "str"
                create_params.append(f"{fname}: Optional[{ftype}] = None")

            params_str = ", ".join(create_params)

            api_routes.append(f'''
# === {name} API Routes ===

@app.get("/api/{name_lower}s")
async def api_list_{name_lower}s(search: str = "", page: int = 1):
    results = Service.list_{name_lower}s(search=search, page=page)
    total = Service.count_{name_lower}s(search=search)
    return {{"items": results, "total": total, "page": page}}

@app.get("/api/{name_lower}s/{{item_id}}")
async def api_get_{name_lower}(item_id: int):
    item = Service.get_{name_lower}(item_id)
    if not item:
        raise HTTPException(status_code=404, detail="{name} not found")
    return item

@app.post("/api/{name_lower}s")
async def api_create_{name_lower}({params_str}):
    item_id = Service.create_{name_lower}({", ".join(f.split(":")[0] for f in ["name:str"] + fields[1:])})
    return {{"id": item_id, "status": "created"}}

@app.put("/api/{name_lower}s/{{item_id}}")
async def api_update_{name_lower}(item_id: int, {params_str}):
    updated = Service.update_{name_lower}(item_id, {", ".join(f.split(":")[0] for f in ["name:str"] + fields[1:])})
    return {{"updated": updated}}

@app.delete("/api/{name_lower}s/{{item_id}}")
async def api_delete_{name_lower}(item_id: int):
    deleted = Service.delete_{name_lower}(item_id)
    return {{"deleted": deleted}}''')

        # Generate HTML routes
        html_routes = []
        for entity in entities[:3]:
            name = entity.get("name", "Item")
            name_lower = name.lower()
            html_routes.append(f'''
@app.get("/{name_lower}s")
async def page_{name_lower}s(request: Request, search: str = "", page: int = 1):
    items = Service.list_{name_lower}s(search=search, page=page)
    total = Service.count_{name_lower}s(search=search)
    return templates.TemplateResponse("list.html", {{
        "request": request,
        "items": items,
        "total": total,
        "page": page,
        "entity_name": "{name}",
        "entity_name_lower": "{name_lower}",
    }})''')

        api_routes_str = "\n".join(api_routes) if api_routes else '''
@app.get("/api/items")
async def api_list_items(search: str = "", page: int = 1):
    results = Service.list_items(search=search, page=page)
    return {"items": results}'''

        html_routes_str = "\n".join(html_routes) if html_routes else '''
@app.get("/items")
async def page_items(request: Request):
    items = Service.list_items()
    return templates.TemplateResponse("list.html", {
        "request": request, "items": items, "entity_name": "Item"
    })'''

        return f'''"""
{project_name} - Main Application
Auto-generated by TITAN OMNISCALE X

Run with: uvicorn main:app --host 0.0.0.0 --port {plan.config_vars.get('port', 8000)} --reload
"""
from fastapi import FastAPI, Request, HTTPException
from fastapi.responses import HTMLResponse, JSONResponse
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates
from typing import Optional
import os

from database import init_db
from services import Service

# ============================================================
#  APP SETUP
# ============================================================

app = FastAPI(
    title="{project_name}",
    description="{plan.template_type.replace('_', ' ').title()} - Generated by TITAN OMNISCALE X",
    version="1.0.0",
)

# Static files and templates
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
app.mount("/static", StaticFiles(directory=os.path.join(BASE_DIR, "static")), name="static")
templates = Jinja2Templates(directory=os.path.join(BASE_DIR, "templates"))

# Initialize database on startup
@app.on_event("startup")
async def startup():
    init_db()


# ============================================================
#  DASHBOARD
# ============================================================

@app.get("/", response_class=HTMLResponse)
async def dashboard(request: Request):
    """Dashboard principal."""
    stats = Service.get_dashboard_stats() if hasattr(Service, 'get_dashboard_stats') else {{}}
    return templates.TemplateResponse("dashboard.html", {{
        "request": request,
        "app_name": "{project_name}",
        "stats": stats,
    }})


# ============================================================
#  API ROUTES
# ============================================================

@app.get("/health")
async def health_check():
    return {{"status": "ok", "app": "{project_name}"}}
{api_routes_str}


# ============================================================
#  HTML PAGES
# ============================================================

{html_routes_str}


# ============================================================
#  ERROR HANDLERS
# ============================================================

@app.exception_handler(404)
async def not_found_handler(request: Request, exc):
    if request.url.path.startswith("/api/"):
        return JSONResponse(status_code=404, content={{"error": "Not found"}})
    return templates.TemplateResponse("dashboard.html", {{
        "request": request, "app_name": "{project_name}", "error": "Page not found"
    }})

@app.exception_handler(500)
async def server_error_handler(request: Request, exc):
    return JSONResponse(status_code=500, content={{"error": "Internal server error"}})


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port={plan.config_vars.get('port', 8000)})
'''
