"""
TITAN OMNISCALE X - Utils Mixin

Helper methods: _fallback_plan, _generate_project_name, list_templates, _gen_readme
"""

import re
import time
from typing import Dict, List


class UtilsMixin:
    """Mixin with utility/helper methods for AppGenerator."""

    def _fallback_plan(self, request: str):
        """Plan de generación fallback sin ThinkingEngine."""
        from src.core.thinking_engine import GenerationPlan

        return GenerationPlan(
            template_type="generic",
            modules=["models", "api", "services", "templates"],
            entities=[{"name": "Item", "fields": ["name:str", "description:str", "created_at:datetime"]}],
            endpoints=[
                {"method": "GET", "path": "/api/items", "desc": "List items"},
                {"method": "POST", "path": "/api/items", "desc": "Create item"},
                {"method": "GET", "path": "/health", "desc": "Health check"},
            ],
            config_vars={"db_name": "app.db", "port": 8000},
            confidence=0.3,
            source="fallback",
        )

    def _generate_project_name(self, template_type: str, request: str) -> str:
        """Genera un nombre de proyecto válido."""
        # Clean request to make a project name
        name = re.sub(r'[^a-zA-Z0-9\s]', '', request.lower())
        words = name.split()[:3]
        if words:
            project_name = "_".join(words)
        else:
            project_name = template_type
        # Ensure it's a valid directory name
        project_name = re.sub(r'[^a-z0-9_]', '_', project_name).strip('_')
        if not project_name:
            project_name = "titan_app"

        # Add timestamp for uniqueness
        import time
        project_name += f"_{int(time.time()) % 100000}"

        return project_name

    # ================================================================
    #  LIST AVAILABLE TEMPLATES
    # ================================================================

    @staticmethod
    def list_templates() -> Dict[str, List[str]]:
        """Lista todos los templates disponibles."""
        return {
            "apps": [
                "web_api - API REST con FastAPI + SQLite",
                "crud_dashboard - Panel CRUD con dashboard",
                "inventory - Sistema de inventario y stock",
                "invoice_billing - Sistema de facturación",
                "crm - Gestión de clientes y ventas",
                "task_manager - Gestión de tareas y proyectos",
                "auth_system - Sistema de autenticación",
                "report_generator - Generador de reportes",
                "notification_service - Servicio de notificaciones",
                "scheduler - Sistema de agenda y citas",
                "chatbot_service - Servicio de chatbot",
                "file_manager - Gestor de archivos",
                "dashboard - Panel de control general",
            ],
            "automations": [
                "email_sender - Envío automático de emails",
                "data_sync - Sincronización de datos",
                "file_watcher - Monitoreo de archivos",
                "webhook_handler - Manejador de webhooks",
                "scheduled_report - Reportes programados",
                "database_backup - Backup automático de BD",
                "api_monitor - Monitor de APIs",
                "notification_dispatcher - Despacho de notificaciones",
            ],
        }

    def _gen_readme(self, plan, project_name: str) -> str:
        """Genera README.md."""
        entity_list = "\n".join(f"- **{e['name']}**: {', '.join(f.split(':')[0] for f in e.get('fields', []))}" for e in plan.entities)
        endpoint_list = "\n".join(f"- `{ep.get('method', 'GET')} {ep.get('path', '/')}` - {ep.get('desc', '')}" for ep in plan.endpoints[:15])

        return f'''# {project_name}

> Auto-generated by **TITAN OMNISCALE X** - {plan.template_type.replace('_', ' ').title()}

## Quick Start

```bash
pip install -r requirements.txt
python main.py
```

Open http://localhost:{plan.config_vars.get('port', 8000)} in your browser.

## Entities

{entity_list if entity_list else "- Generic Item"}

## API Endpoints

{endpoint_list if endpoint_list else "- GET /health - Health check"}

## Tech Stack

- **FastAPI** - Modern async web framework
- **SQLite** - Embedded database (no server needed)
- **Jinja2** - HTML templates
- **uvicorn** - ASGI server

## Project Structure

```
{project_name}/
  main.py           # FastAPI application
  models.py         # Data models
  database.py       # Database configuration
  services.py       # Business logic
  config.py         # Configuration
  templates/        # HTML templates
  static/           # CSS/JS assets
  data/             # SQLite database (auto-created)
```
'''
