"""
Contextual code generation for CodeGenerator.
"""

import re
from src.core.shared.contracts import OperationType, GoalType


class ContextualMixin:
    """Contextual code generation for CodeGenerator."""

    def generate_intelligent_code(self, intent, ast_analysis, lang):
        """Genera codigo usando datos del AST, solver y MCTS."""
        return self.generate_contextual_code(intent, ast_analysis, None, lang)

    def generate_contextual_code(self, intent, ast_analysis, plan, lang):
        """Genera codigo contextual usando datos del pipeline."""
        if plan is not None:
            return self.generate_pipeline_driven_code(intent, ast_analysis, plan, lang)

        target = intent.target
        safe_target = re.sub(r'[^\w]', '_', target.replace('.py', '').replace('.kt', '').replace('.go', '').replace('.js', '')) if target != "unknown" else "module"

        existing_functions = ast_analysis.get("function_names", []) if ast_analysis else []
        existing_classes = ast_analysis.get("class_names", []) if ast_analysis else []
        existing_connections = ast_analysis.get("connections", []) if ast_analysis else []
        max_complexity = ast_analysis.get("max_complexity", 0) if ast_analysis else 0

        needed_imports = set()
        for conn in existing_connections:
            conn_str = str(conn)
            if "extends:" in conn_str:
                parent = conn_str.replace("extends:", "")
                needed_imports.add(parent)
            elif "method:" not in conn_str:
                needed_imports.add(conn_str)

        if lang == "python":
            return self.generate_python_contextual(intent, ast_analysis, safe_target,
                                                     existing_functions, existing_classes,
                                                     existing_connections, needed_imports,
                                                     max_complexity)
        elif lang == "kotlin":
            return self.generate_kotlin_contextual(intent, safe_target, existing_classes)
        elif lang == "go":
            return self.generate_go_contextual(intent, safe_target)
        elif lang == "javascript":
            return self.generate_javascript_contextual(intent, safe_target)
        return self.generate_python_contextual(intent, ast_analysis, safe_target,
                                                 existing_functions, existing_classes,
                                                 existing_connections, needed_imports,
                                                 max_complexity)

    def generate_python_contextual(self, intent, ast_analysis, safe_target,
                                     existing_functions, existing_classes,
                                     existing_connections, needed_imports,
                                     max_complexity):
        """Genera codigo Python contextual."""
        orch = self._orchestrator
        if intent.op == OperationType.CREATE:
            if intent.goal == GoalType.SECURITY_HARDEN:
                return self.generate_security_module(safe_target)
            else:
                return self.generate_feature_module(safe_target, existing_functions,
                                                      existing_classes, needed_imports)
        elif intent.op in [OperationType.REFACTOR, OperationType.OPTIMIZE]:
            if intent.raw_code:
                return orch._code_transform.refactor_python(intent.raw_code, ast_analysis)
            return f'# TITAN OMNISCALE X - Optimized version of {safe_target}\n# No original code provided\n'
        elif intent.op == OperationType.DEBUG:
            if intent.raw_code:
                return orch._code_transform.fix_python(intent.raw_code, ast_analysis)
            return f'# TITAN OMNISCALE X - Debug suggestions for {safe_target}\n# Provide code to analyze errors\n'
        return f'# TITAN OMNISCALE X - {intent.op} operation on {safe_target}\n'

    @staticmethod
    def generate_security_module(safe_target):
        """Genera modulo de seguridad con patrones modernos."""
        return f'''"""
{safe_target} - Security-Hardened Module
Generated by TITAN OMNISCALE X
"""
import hashlib
import secrets
import hmac
from typing import Optional


class SecurityManager:
    """Security manager with modern patterns."""

    def __init__(self, secret_key: Optional[str] = None):
        self._secret_key = secret_key or secrets.token_hex(32)

    def hash_password(self, password: str, salt: Optional[str] = None) -> str:
        """Hash password with salt using PBKDF2."""
        if salt is None:
            salt = secrets.token_hex(16)
        dk = hashlib.pbkdf2_hmac(
            'sha256', password.encode(), salt.encode(), 100000
        )
        return f"{{salt}}:{{dk.hex()}}"

    def verify_password(self, password: str, stored_hash: str) -> bool:
        """Verify password against stored hash."""
        try:
            salt, hash_val = stored_hash.split(':')
            dk = hashlib.pbkdf2_hmac(
                'sha256', password.encode(), salt.encode(), 100000
            )
            return hmac.compare_digest(dk.hex(), hash_val)
        except (ValueError, AttributeError):
            return False

    def generate_token(self, length: int = 32) -> str:
        """Generate cryptographically secure token."""
        return secrets.token_urlsafe(length)


if __name__ == "__main__":
    manager = SecurityManager()
    token = manager.generate_token()
    print(f"Token generated: {{token}}")
'''

    @staticmethod
    def generate_feature_module(safe_target, existing_functions, existing_classes, needed_imports):
        """Genera modulo de feature contextual que integra con codigo existente."""
        import_lines = [
            "from dataclasses import dataclass, field",
            "from typing import List, Optional, Dict, Any",
        ]
        for imp in needed_imports:
            if imp and imp not in ["object", "str", "int", "bool", "list", "dict"]:
                import_lines.append(f"# from your_project import {imp}  # Detected dependency")
        extra_methods = ""
        if existing_functions:
            extra_methods = f'''
    # Contextual integration with existing code
    # Detected functions: {", ".join(existing_functions[:5])}
    # Detected classes: {", ".join(existing_classes[:5]) if existing_classes else "none"}
'''
        return f'''"""
{safe_target} - Feature Module
Generated by TITAN OMNISCALE X (Contextual Generation)
"""
{chr(10).join(import_lines)}


@dataclass
class Config:
    """Module configuration."""
    name: str = "{safe_target}"
    debug: bool = False
    max_retries: int = 3


@dataclass
class Result:
    """Operation result with error handling."""
    success: bool
    data: Any = None
    error: Optional[str] = None


class {safe_target.capitalize()}Manager:
    """Main module manager."""
{extra_methods}
    def __init__(self, config: Optional[Config] = None):
        self.config = config or Config()
        self._initialized = False

    def initialize(self) -> Result:
        """Initialize the module."""
        try:
            self._initialized = True
            return Result(success=True, data={{"status": "initialized"}})
        except Exception as e:
            return Result(success=False, error=str(e))

    def execute(self, payload: Dict[str, Any]) -> Result:
        """Execute main operation."""
        if not self._initialized:
            return Result(success=False, error="Module not initialized")
        try:
            result_data = self._process(payload)
            return Result(success=True, data=result_data)
        except Exception as e:
            return Result(success=False, error=str(e))

    def _process(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        """Internal processing."""
        return {{"processed": True, "input": payload}}


if __name__ == "__main__":
    manager = {safe_target.capitalize()}Manager()
    result = manager.initialize()
    print(f"Initialization: {{result.success}}")
'''

    @staticmethod
    def generate_kotlin_contextual(intent, safe_target, existing_classes):
        target = safe_target if safe_target else "Module"
        return f'''// {target} - Generated by TITAN OMNISCALE X
package com.titan.{target.lower()}

data class {target}Config(
    val name: String = "{target}",
    val debug: Boolean = false,
    val maxRetries: Int = 3
)

class {target}Manager(private val config: {target}Config = {target}Config()) {{
    private var initialized = false

    fun initialize(): Result<Boolean> {{
        return try {{
            initialized = true
            Result.success(true)
        }} catch (e: Exception) {{
            Result.failure(e)
        }}
    }}

    fun execute(payload: Map<String, Any>): Result<Map<String, Any>> {{
        if (!initialized) {{
            return Result.failure(IllegalStateException("Not initialized"))
        }}
        return Result.success(mapOf("processed" to true, "input" to payload))
    }}
}}

fun main() {{
    val manager = {target}Manager()
    manager.initialize()
    println("${{target}} initialized")
}}
'''

    @staticmethod
    def generate_go_contextual(intent, safe_target):
        target = safe_target if safe_target else "module"
        return f'''// {target} - Generated by TITAN OMNISCALE X
package main

import "fmt"

type Config struct {{
        Name      string
        Debug     bool
        MaxRetries int
}}

type Manager struct {{
        config Config
        initialized bool
}}

func NewManager(config Config) *Manager {{
        return &Manager{{config: config}}
}}

func (m *Manager) Initialize() error {{
        m.initialized = true
        return nil
}}

func (m *Manager) Execute(payload map[string]interface{{}}) (map[string]interface{{}}, error) {{
        if !m.initialized {{
                return nil, fmt.Errorf("not initialized")
        }}
        return map[string]interface{{}}{{"processed": true, "input": payload}}, nil
}}

func main() {{
        manager := NewManager(Config{{Name: "{target}"}})
        manager.Initialize()
        fmt.Println("{target} initialized")
}}
'''

    @staticmethod
    def generate_javascript_contextual(intent, safe_target):
        target = safe_target if safe_target else "module"
        return f'''// {target} - Generated by TITAN OMNISCALE X

class {target.capitalize()}Manager {{
    constructor(config = {{}}) {{
        this.config = {{
            name: "{target}",
            debug: false,
            maxRetries: 3,
            ...config
        }};
        this.initialized = false;
    }}

    async initialize() {{
        this.initialized = true;
        return {{ success: true }};
    }}

    async execute(payload) {{
        if (!this.initialized) {{
            throw new Error("Not initialized");
        }}
        return {{ processed: true, input: payload }};
    }}
}}

module.exports = {{ {target.capitalize()}Manager }};
'''
