"""
DeterministicPipeline - Pipeline que hace TODAS las tareas sin IA.

Reemplaza las 7 tareas bounded de MiniAIEngine con versiones
puramente determinísticas que son más rápidas y más confiables.

Tareas reemplazadas:
  1. classify_intent()    → Keyword scoring + evidencia
  2. extract_entities()   → Regex extraction + patrones
  3. suggest_pattern()    → Lookup table + heuristicas
  4. fill_template_gaps() → Context mapping + defaults
  5. generate_pattern()   → Template library + composición
  6. explain_violation()  → Formateo automático + catálogo
  7. describe_subtask()   → Composición automática de nombre

Ventajas sobre la versión con IA:
  - 0ms de latencia LLM (antes 3-8s por llamada)
  - 0% de alucinaciones
  - 0% de parsing errors (no depende de output de IA)
  - Determinístico: mismo input → mismo output, siempre
  - Funciona sin GPU, sin modelo, sin dependencias externas
"""

import re
import os
import json
import logging
from typing import Dict, Any, List, Optional

from .types import DeterministicResult, Evidence, EvidenceType, Verdict
from .evidence_collector import EvidenceCollector, OP_KEYWORDS, GOAL_KEYWORDS

logger = logging.getLogger(__name__)

# === Tabla de extensión a lenguaje ===
EXT_LANG_MAP = {
    ".py": "python", ".kt": "kotlin", ".go": "go",
    ".js": "javascript", ".ts": "typescript", ".java": "java",
    ".rs": "rust", ".rb": "ruby", ".cpp": "cpp", ".c": "c",
    ".h": "c", ".hpp": "cpp", ".swift": "swift", ".scala": "scala",
}

# === Tabla de patrones de código por lenguaje ===
PATTERN_LIBRARY = {
    "python": {
        "async_await": "async def {name}({params}):\n    result = await {operation}({params})\n    return result\n",
        "validator": "def {name}(data: dict) -> bool:\n    required = {required_fields}\n    return all(k in data for k in required)\n",
        "repository": "class {class_name}:\n    def __init__(self, db):\n        self.db = db\n    def get_by_id(self, id: str):\n        return self.db.query(id)\n",
        "factory": "def create_{name}(type_: str):\n    handlers = {handler_map}\n    return handlers.get(type_, DefaultHandler)\n",
        "middleware": "def {name}(func):\n    def wrapper(*args, **kwargs):\n        pre_process(*args)\n        result = func(*args, **kwargs)\n        post_process(result)\n        return result\n    return wrapper\n",
        "observer": "class {class_name}:\n    def __init__(self):\n        self._observers = []\n    def subscribe(self, observer):\n        self._observers.append(observer)\n    def notify(self, event):\n        for obs in self._observers:\n            obs.on_event(event)\n",
        "security": "import hashlib, secrets\n\ndef hash_password(password: str) -> str:\n    salt = secrets.token_hex(16)\n    return hashlib.sha256((salt + password).encode()).hexdigest()\n",
        "cache": "from functools import lru_cache\n\n@lru_cache(maxsize=128)\ndef {name}(key):\n    return expensive_lookup(key)\n",
        "singleton": "class {class_name}:\n    _instance = None\n    def __new__(cls):\n        if cls._instance is None:\n            cls._instance = super().__new__(cls)\n        return cls._instance\n",
        "default": "def {name}(data):\n    \"\"\"Generated by ZENIC LOGIC v17\"\"\"\n    return data\n",
    },
    "javascript": {
        "async_await": "async function {name}({params}) {\n    const result = await {operation}({params});\n    return result;\n}\n",
        "validator": "function {name}(data) {\n    const required = {required_fields};\n    return required.every(k => k in data);\n}\n",
        "default": "function {name}(data) {\n    return data;\n}\n",
    },
    "typescript": {
        "default": "function {name}(data: any): any {\n    return data;\n}\n",
    },
}

# === Catálogo de violaciones con explicaciones ===
VIOLATION_CATALOG = {
    "exec_call": "Use of exec() allows arbitrary code execution, which is a critical security risk.",
    "eval_call": "Use of eval() allows arbitrary code execution, which is a critical security risk.",
    "import_call": "Dynamic import via __import__() can load untrusted modules at runtime.",
    "os_system": "os.system() executes shell commands, vulnerable to injection attacks.",
    "subprocess_call": "subprocess calls can execute arbitrary system commands.",
    "pickle_load": "pickle.loads() can deserialize malicious objects leading to RCE.",
    "yaml_unsafe": "yaml.load() without SafeLoader can execute arbitrary Python code.",
    "sensitive_file": "Access to sensitive system files (/etc, /proc, /sys) detected.",
    "rm_rf": "Dangerous rm -rf command detected, can destroy entire filesystems.",
    "socket_raw": "Raw socket creation detected, may indicate network-level exploits.",
    "null_pointer": "Potential null/None dereference detected.",
    "type_mismatch": "Type mismatch detected in function call.",
    "unreachable": "Unreachable code detected after return statement.",
    "unused_import": "Unused import detected.",
}

# === Mapa de heuristicas para sugerir patrones ===
PATTERN_HEURISTICS = [
    (["async", "await", "coroutine", "asincrono"], "async_await"),
    (["validate", "validar", "check", "verify", "verificar"], "validator"),
    (["repository", "repo", "database", "db", "base de datos"], "repository"),
    (["factory", "create", "creator", "fabrica"], "factory"),
    (["middleware", "interceptor", "pipeline"], "middleware"),
    (["observer", "subscribe", "event", "listen", "escuchar"], "observer"),
    (["security", "auth", "login", "token", "seguridad"], "security"),
    (["cache", "memoize", "store", "cachear"], "cache"),
    (["singleton", "single", "unique", "unico"], "singleton"),
    (["test", "testing", "prueba", "spec"], "default"),
]


class DeterministicPipeline:
    """
    Pipeline determinístico que reemplaza las 7 tareas de MiniAIEngine.

    Todas las operaciones son puramente algorítmicas:
    - No usan el modelo LLM
    - Son determinísticas (mismo input → mismo output)
    - Son más rápidas que las versiones con IA
    - Son más confiables (no alucinan)

    Cuando el resultado no es suficientemente confiable,
    devuelve confidence baja para que el ConsensusResolver
    decida si necesita arbitraje de IA.
    """

    def __init__(self):
        self._evidence_collector = EvidenceCollector()

    # ================================================================
    #  TASK 1: classify_intent (reemplaza MiniAIEngine.classify_intent)
    # ================================================================

    def classify_intent(self, text: str) -> DeterministicResult:
        """
        Clasifica la intención del usuario usando keyword scoring.

        Reemplaza: MiniAIEngine.classify_intent() (que usaba 2 llamadas LLM)
        Mejora: 0ms de latencia, 0% de errores de parsing, determinístico
        """
        evidence = self._evidence_collector.collect_intent_evidence(text)
        result = self._evidence_collector.collect_goal_evidence(text)
        all_evidence = evidence + result

        from .consensus_resolver import ConsensusResolver
        resolver = ConsensusResolver()
        return resolver.resolve_classification(text, all_evidence)

    # ================================================================
    #  TASK 2: extract_entities (reemplaza MiniAIEngine.extract_entities)
    # ================================================================

    def extract_entities(self, text: str) -> DeterministicResult:
        """
        Extrae entidades (archivo, lenguaje, función) usando regex.

        Reemplaza: MiniAIEngine.extract_entities() (que usaba LLM con JSON)
        Mejora: 0ms de latencia, 0% de JSON parse errors
        """
        # File extraction
        file_match = re.search(r'([\w\.-]+\.(py|kt|go|js|ts|java|rs|rb|cpp|c|h))', text)
        file_name = file_match.group(1) if file_match else ""

        # Language from extension
        ext = os.path.splitext(file_name)[1] if file_name else ""
        lang = EXT_LANG_MAP.get(ext, "unknown")

        # Function name extraction
        func_match = re.search(r'(?:function|func|def|fun)\s+(\w+)', text)
        function = func_match.group(1) if func_match else None

        # Language from keywords (if no file extension)
        if lang == "unknown":
            text_lower = text.lower()
            if "python" in text_lower or "def " in text:
                lang = "python"
            elif "javascript" in text_lower or "function " in text or "const " in text:
                lang = "javascript"
            elif "typescript" in text_lower or ": string" in text or ": number" in text:
                lang = "typescript"
            elif "kotlin" in text_lower or "fun " in text:
                lang = "kotlin"
            elif "golang" in text_lower or "go " in text_lower or "func " in text:
                lang = "go"

        confidence = 0.9 if file_name else (0.6 if lang != "unknown" else 0.2)

        return DeterministicResult(
            task_name="extract_entities",
            success=True,
            result={
                "file": file_name,
                "lang": lang,
                "function": function,
            },
            confidence=confidence,
            source="deterministic",
        )

    # ================================================================
    #  TASK 3: suggest_pattern (reemplaza MiniAIEngine.suggest_pattern)
    # ================================================================

    def suggest_pattern(self, target: str, description: str) -> DeterministicResult:
        """
        Sugiere un patrón de código usando heurísticas.

        Reemplaza: MiniAIEngine.suggest_pattern() (que usaba LLM)
        Mejora: Siempre devuelve un patrón válido, 0% de respuestas basura
        """
        desc_lower = description.lower()
        target_lower = target.lower()
        combined = f"{desc_lower} {target_lower}"

        for keywords, pattern_name in PATTERN_HEURISTICS:
            if any(kw in combined for kw in keywords):
                return DeterministicResult(
                    task_name="suggest_pattern",
                    success=True,
                    result=f"{pattern_name}_pattern",
                    confidence=0.8,
                    source="deterministic",
                )

        return DeterministicResult(
            task_name="suggest_pattern",
            success=True,
            result="default_pattern",
            confidence=0.3,
            source="deterministic",
        )

    # ================================================================
    #  TASK 4: fill_template_gaps (reemplaza MiniAIEngine.fill_template_gaps)
    # ================================================================

    def fill_template_gaps(self, template: str,
                           context: Dict[str, Any]) -> DeterministicResult:
        """
        Rellena huecos de template con contexto y defaults.

        Reemplaza: MiniAIEngine.fill_template_gaps() (que usaba LLM para JSON)
        Mejora: Siempre rellena todos los huecos, 0% de JSON parse errors
        """
        gaps = re.findall(r'__GAP_(\w+)__', template)
        if not gaps:
            return DeterministicResult(
                task_name="fill_template_gaps",
                success=True,
                result=template,
                confidence=1.0,
                source="deterministic",
            )

        defaults = {
            "NAME": context.get("name", "generated"),
            "CLASS_NAME": context.get("class_name", "GeneratedClass"),
            "FUNC_NAME": context.get("func_name", "generated_function"),
            "RETURN_TYPE": context.get("return_type", "Any"),
            "PARAMS": context.get("params", "self"),
            "BODY": context.get("body", "pass"),
            "DOCSTRING": context.get("docstring", "Generated by ZENIC LOGIC v17"),
            "IMPORT": context.get("import_", "import os"),
            "VAR_NAME": context.get("var_name", "result"),
            "TYPE": context.get("type", "str"),
            "OPERATION": context.get("operation", "process"),
            "REQUIRED_FIELDS": str(context.get("required_fields", "['id', 'name']")),
            "HANDLER_MAP": str(context.get("handler_map", "{}")),
        }

        result = template
        filled_count = 0
        for gap in gaps:
            gap_lower = gap.lower()
            # Try context first (case-insensitive)
            value = None
            if gap_lower in context:
                value = context[gap_lower]
            elif gap in context:
                value = context[gap]
            elif gap in defaults:
                value = defaults[gap]
            else:
                value = f"placeholder_{gap_lower}"

            result = result.replace(f"__GAP_{gap}__", str(value))
            filled_count += 1

        all_filled = not re.search(r'__GAP_\w+__', result)
        confidence = 1.0 if all_filled else 0.5

        return DeterministicResult(
            task_name="fill_template_gaps",
            success=True,
            result=result,
            confidence=confidence,
            source="deterministic",
        )

    # ================================================================
    #  TASK 5: generate_pattern (reemplaza MiniAIEngine.generate_pattern)
    # ================================================================

    def generate_pattern(self, pattern_desc: str,
                         language: str = "python",
                         context: Optional[Dict[str, Any]] = None) -> DeterministicResult:
        """
        Genera un snippet de código desde la librería de templates.

        Reemplaza: MiniAIEngine.generate_pattern() (que usaba LLM ~20 líneas)
        Mejora: Código siempre correcto, compilable, sin alucinaciones

        NOTA: La IA NUNCA genera código. El código viene de templates
        probados y validados, no de generación probabilística.
        """
        ctx = context or {}
        lang_patterns = PATTERN_LIBRARY.get(language, PATTERN_LIBRARY["python"])

        # Buscar patrón por descripción
        desc_lower = pattern_desc.lower()
        pattern_name = "default"

        for keywords, name in PATTERN_HEURISTICS:
            if any(kw in desc_lower for kw in keywords):
                pattern_name = name
                break

        # Obtener template
        template = lang_patterns.get(pattern_name, lang_patterns.get("default", ""))

        # Rellenar placeholders simples
        name = ctx.get("name", ctx.get("func_name", "generated"))
        class_name = ctx.get("class_name", "GeneratedClass")
        params = ctx.get("params", "data")
        operation = ctx.get("operation", "process")

        result = template.format(
            name=name,
            class_name=class_name,
            params=params,
            operation=operation,
            required_fields=str(ctx.get("required_fields", "['id', 'name']")),
            handler_map=str(ctx.get("handler_map", "{}")),
        )

        confidence = 0.9 if pattern_name != "default" else 0.5

        return DeterministicResult(
            task_name="generate_pattern",
            success=True,
            result=result,
            confidence=confidence,
            source="deterministic",
        )

    # ================================================================
    #  TASK 6: explain_violation (reemplaza MiniAIEngine.explain_violation)
    # ================================================================

    def explain_violation(self, code: str,
                          violations: List[str]) -> DeterministicResult:
        """
        Explica violaciones usando el catálogo de mensajes.

        Reemplaza: MiniAIEngine.explain_violation() (que usaba LLM ~50 tokens)
        Mejora: Explicaciones consistentes, sin variabilidad
        """
        if not violations:
            return DeterministicResult(
                task_name="explain_violation",
                success=True,
                result="No violations detected.",
                confidence=1.0,
                source="deterministic",
            )

        explanations = []
        for v in violations[:5]:  # Max 5 violations
            v_lower = v.lower()
            # Buscar en catálogo
            explanation = None
            for key, msg in VIOLATION_CATALOG.items():
                if key in v_lower or any(kw in v_lower for kw in key.split("_")):
                    explanation = msg
                    break

            if not explanation:
                explanation = f"Code violation detected: {v}"
            explanations.append(explanation)

        result = "; ".join(explanations)

        return DeterministicResult(
            task_name="explain_violation",
            success=True,
            result=result,
            confidence=0.95,
            source="deterministic",
        )

    # ================================================================
    #  TASK 7: describe_subtask (reemplaza MiniAIEngine.describe_subtask)
    # ================================================================

    def describe_subtask(self, target: str, action: str,
                         context: str = "") -> DeterministicResult:
        """
        Genera un nombre descriptivo para un subtask.

        Reemplaza: MiniAIEngine.describe_subtask() (que usaba LLM ~30 tokens)
        Mejora: Nombres consistentes y limpios
        """
        safe_target = re.sub(r'[^a-z0-9_]', '_', target.lower()).strip('_')
        safe_action = re.sub(r'[^a-z0-9_]', '_', action.lower()).strip('_')

        # Limpiar underscores duplicados
        name = re.sub(r'_+', '_', f"{safe_action}_{safe_target}").strip('_')

        if not name or len(name) < 3:
            name = "unnamed_subtask"

        return DeterministicResult(
            task_name="describe_subtask",
            success=True,
            result=name,
            confidence=0.9,
            source="deterministic",
        )

    # ================================================================
    #  UTILITY: Batch execute all 7 tasks
    # ================================================================

    def execute_all(self, text: str, code: str = "",
                    language: str = "python",
                    context: Optional[Dict[str, Any]] = None) -> Dict[str, DeterministicResult]:
        """
        Ejecuta todas las tareas determinísticas en secuencia.

        Returns:
            Diccionario con los resultados de cada tarea
        """
        ctx = context or {}
        results = {}

        results["classify"] = self.classify_intent(text)
        results["extract"] = self.extract_entities(text)

        target = results["extract"].result.get("file", "target")
        results["pattern"] = self.suggest_pattern(target, text)

        template = ctx.get("template", "")
        if template:
            results["fill"] = self.fill_template_gaps(template, ctx)
        else:
            results["fill"] = DeterministicResult(
                task_name="fill_template_gaps", success=True,
                result="", confidence=1.0, source="deterministic",
            )

        if code:
            results["generate"] = self.generate_pattern(
                results["pattern"].result, language, ctx
            )
            violations = ctx.get("violations", [])
            results["explain"] = self.explain_violation(code, violations)
        else:
            results["generate"] = DeterministicResult(
                task_name="generate_pattern", success=True,
                result="", confidence=1.0, source="deterministic",
            )
            results["explain"] = DeterministicResult(
                task_name="explain_violation", success=True,
                result="No code to validate.", confidence=1.0,
                source="deterministic",
            )

        results["subtask"] = self.describe_subtask(target, "process")

        return results
