"""
SchemaDesigner Python model and migration generation mixin.
"""

import logging
from typing import List

from ._imports import (
    ColumnDef, TableDef, SchemaDef, _sanitize_identifier, logger,
)


class PythonGenMixin:
    """Python model and migration generation methods for SchemaDesigner."""

    # ================================================================
    #  PYTHON MODEL GENERATION
    # ================================================================

    def generate_models(self, schema: SchemaDef) -> str:
        """Genera modelos Python (dataclasses) desde el esquema."""
        model_classes = []

        for table in schema.tables:
            fields = []
            for col in table.columns:
                if col.autoincrement:
                    fields.append(f"    {col.name}: Optional[int] = None  # Auto-generated")
                elif col.name in ("created_at", "updated_at"):
                    fields.append(f"    {col.name}: Optional[str] = None  # Auto-set")
                elif col.foreign_key:
                    fields.append(f"    {col.name}: Optional[int] = None  # FK -> {col.foreign_key}")
                else:
                    py_type = col.python_type
                    default = 'None' if col.nullable else (
                        '0' if py_type == 'int' else
                        '0.0' if py_type == 'float' else
                        'False' if py_type == 'bool' else '""'
                    )
                    fields.append(f"    {col.name}: Optional[{py_type}] = {default}")

            fields_str = "\n".join(fields)
            class_name = "".join(w.capitalize() for w in table.name.split("_"))

            model_classes.append(f'''@dataclass
class {class_name}:
    """Modelo para la tabla {table.name}."""
{fields_str}

    def to_dict(self) -> Dict[str, Any]:
        return {{k: v for k, v in asdict(self).items() if v is not None}}

    @classmethod
    def from_row(cls, row: Dict[str, Any]) -> "{class_name}":
        return cls(**{{k: v for k, v in row.items() if k in cls.__dataclass_fields__}})''')

        imports = """from dataclasses import dataclass, asdict, field
from typing import Optional, List, Dict, Any
from datetime import datetime"""

        return f'"""Database Models - Auto-generated by TITAN OMNISCALE X"""\n\n{imports}\n\n\n' + "\n\n\n".join(model_classes)

    # ================================================================
    #  MIGRATION GENERATION
    # ================================================================

    def generate_migration(self, old_schema: SchemaDef, new_schema: SchemaDef,
                           version: int = 2) -> str:
        """Genera SQL de migración entre dos versiones del esquema."""
        statements = [f"-- Migration v{version - 1} -> v{version}"]

        old_tables = {t.name: t for t in old_schema.tables}
        new_tables = {t.name: t for t in new_schema.tables}

        # New tables
        for name, table in new_tables.items():
            if name not in old_tables:
                statements.append(f"-- New table: {name}")
                statements.append(self._table_to_sql(table))

        # Modified tables
        for name, new_table in new_tables.items():
            if name in old_tables:
                old_table = old_tables[name]
                old_cols = {c.name: c for c in old_table.columns}
                new_cols = {c.name: c for c in new_table.columns}

                # New columns
                for col_name, col in new_cols.items():
                    if col_name not in old_cols:
                        statements.append(
                            f"ALTER TABLE {_sanitize_identifier(name)} ADD COLUMN {_sanitize_identifier(col.name)} {col.sql_type}"
                            + (" NOT NULL" if not col.nullable else "")
                            + (f" DEFAULT {col.default}" if col.default else "") + ";"
                        )

        # Dropped tables
        for name in old_tables:
            if name not in new_tables:
                statements.append(f"DROP TABLE IF EXISTS {_sanitize_identifier(name)};")

        return "\n\n".join(statements)

    def _table_to_sql(self, table: TableDef) -> str:
        """Convierte una tabla a SQL CREATE TABLE."""
        col_defs = []
        for col in table.columns:
            col_sql = f"{_sanitize_identifier(col.name)} {col.sql_type}"
            if col.primary_key:
                col_sql += " PRIMARY KEY AUTOINCREMENT"
            if not col.nullable and not col.primary_key:
                col_sql += " NOT NULL"
            if col.unique:
                col_sql += " UNIQUE"
            col_defs.append(col_sql)

        return f"CREATE TABLE IF NOT EXISTS {_sanitize_identifier(table.name)} (\n    " + ",\n    ".join(col_defs) + "\n);"
