"""
Builtin block registration mixin for TemplateEngine.
"""

from ._imports import TemplateBlock


class BuiltinMixin:
    """Builtin block registration for TemplateEngine."""

    def _register_builtin_blocks(self):
        """Registra los bloques de codigo pre-construidos."""
        builtin_blocks = [
            TemplateBlock(
                name="invoice_calculator",
                category="business_logic",
                description="Calculo de facturas con impuestos, descuentos y totales",
                inputs=["items", "tax_rate", "discount"],
                outputs=["subtotal", "tax_amount", "discount_amount", "total"],
                dependencies=[],
                template_path="blocks/business_logic/invoice_calculator.py.j2",
            ),
            TemplateBlock(
                name="inventory_tracker",
                category="business_logic",
                description="Seguimiento de inventario con alertas de stock bajo",
                inputs=["product_id", "quantity_change"],
                outputs=["new_quantity", "alerts"],
                dependencies=[],
                template_path="blocks/business_logic/inventory_tracker.py.j2",
            ),
            TemplateBlock(
                name="crm_pipeline",
                category="business_logic",
                description="Pipeline de ventas con etapas y conversion",
                inputs=["lead_data", "stage"],
                outputs=["updated_lead", "next_action"],
                dependencies=[],
                template_path="blocks/business_logic/crm_pipeline.py.j2",
            ),
            TemplateBlock(
                name="task_scheduler",
                category="business_logic",
                description="Priorizacion y asignacion de tareas",
                inputs=["tasks", "resources"],
                outputs=["schedule", "assignments"],
                dependencies=[],
                template_path="blocks/business_logic/task_scheduler.py.j2",
            ),
            TemplateBlock(
                name="report_generator",
                category="business_logic",
                description="Generacion de reportes desde datos",
                inputs=["data", "template", "format"],
                outputs=["report_content", "metadata"],
                dependencies=[],
                template_path="blocks/business_logic/report_generator.py.j2",
            ),
            TemplateBlock(
                name="notification_manager",
                category="business_logic",
                description="Gestion de notificaciones multi-canal",
                inputs=["recipient", "message", "channels"],
                outputs=["delivery_status"],
                dependencies=["email_smtp", "telegram_bot"],
                template_path="blocks/business_logic/notification_manager.py.j2",
            ),
            TemplateBlock(
                name="data_analyzer",
                category="business_logic",
                description="Analisis estadistico y metricas de datos",
                inputs=["dataset", "metrics"],
                outputs=["analysis_result", "summary"],
                dependencies=[],
                template_path="blocks/business_logic/data_analyzer.py.j2",
            ),
            # Integration blocks
            TemplateBlock(
                name="email_smtp",
                category="integrations",
                description="Envio real de emails via SMTP",
                inputs=["to", "subject", "body", "html"],
                outputs=["message_id", "status"],
                dependencies=[],
                template_path="blocks/integrations/email_smtp.py.j2",
            ),
            TemplateBlock(
                name="whatsapp_api",
                category="integrations",
                description="Envio de mensajes WhatsApp Business API",
                inputs=["phone", "message", "template"],
                outputs=["message_id", "status"],
                dependencies=[],
                template_path="blocks/integrations/whatsapp_api.py.j2",
            ),
            TemplateBlock(
                name="stripe_payments",
                category="integrations",
                description="Procesamiento de pagos con Stripe",
                inputs=["amount", "currency", "customer_id"],
                outputs=["payment_id", "status"],
                dependencies=[],
                template_path="blocks/integrations/stripe_payments.py.j2",
            ),
            TemplateBlock(
                name="google_sheets",
                category="integrations",
                description="Lectura y escritura de Google Sheets",
                inputs=["sheet_id", "range", "data"],
                outputs=["rows", "status"],
                dependencies=[],
                template_path="blocks/integrations/google_sheets.py.j2",
            ),
            TemplateBlock(
                name="telegram_bot",
                category="integrations",
                description="Bot de Telegram para notificaciones",
                inputs=["chat_id", "message"],
                outputs=["message_id", "status"],
                dependencies=[],
                template_path="blocks/integrations/telegram_bot.py.j2",
            ),
            TemplateBlock(
                name="webhook_server",
                category="integrations",
                description="Servidor webhook para recibir notificaciones",
                inputs=["path", "handler"],
                outputs=["endpoint_url", "status"],
                dependencies=[],
                template_path="blocks/integrations/webhook_server.py.j2",
            ),
            TemplateBlock(
                name="pdf_generator",
                category="integrations",
                description="Generacion de PDFs desde HTML/templates",
                inputs=["template", "data", "output_path"],
                outputs=["pdf_path", "status"],
                dependencies=[],
                template_path="blocks/integrations/pdf_generator.py.j2",
            ),
            # Auth blocks
            TemplateBlock(
                name="jwt_auth",
                category="auth",
                description="Autenticacion JWT completa con login, registro, refresh",
                inputs=["username", "password", "role"],
                outputs=["token", "user_id", "role"],
                dependencies=[],
                template_path="blocks/auth/jwt_auth.py.j2",
            ),
            TemplateBlock(
                name="api_key_auth",
                category="auth",
                description="Autenticacion por API key",
                inputs=["api_key"],
                outputs=["authenticated", "identity"],
                dependencies=[],
                template_path="blocks/auth/api_key_auth.py.j2",
            ),
            TemplateBlock(
                name="rbac",
                category="auth",
                description="Control de acceso basado en roles",
                inputs=["user_role", "resource", "action"],
                outputs=["allowed", "reason"],
                dependencies=["jwt_auth"],
                template_path="blocks/auth/rbac.py.j2",
            ),
            # Data blocks
            TemplateBlock(
                name="crud_service",
                category="data",
                description="Servicio CRUD con SQL parametrizado y validacion",
                inputs=["entity", "data"],
                outputs=["result", "status"],
                dependencies=[],
                template_path="blocks/data/crud_service.py.j2",
            ),
            TemplateBlock(
                name="migration",
                category="data",
                description="Sistema de migraciones incrementales",
                inputs=["schema_version", "changes"],
                outputs=["migration_sql", "status"],
                dependencies=[],
                template_path="blocks/data/migration.py.j2",
            ),
            TemplateBlock(
                name="backup_restore",
                category="data",
                description="Backup y restauracion de base de datos",
                inputs=["db_path", "backup_dir"],
                outputs=["backup_path", "status"],
                dependencies=[],
                template_path="blocks/data/backup_restore.py.j2",
            ),
            TemplateBlock(
                name="seed_data",
                category="data",
                description="Generacion de datos iniciales/seed",
                inputs=["schema", "count"],
                outputs=["insert_sql", "status"],
                dependencies=[],
                template_path="blocks/data/seed_data.py.j2",
            ),
        ]
        for block in builtin_blocks:
            self.register_block(block)
