name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install system deps
        run: |
          sudo apt-get update -qq
          sudo apt-get install -yq autoconf automake libtool pkg-config \
            zlib1g-dev libncurses5-dev libncursesw5-dev cmake \
            libffi-dev libssl-dev libltdl-dev liblzma-dev libsqlite3-dev uuid-dev \
            zip unzip openjdk-17-jdk

      - name: Install Python deps
        run: |
          pip install --upgrade pip setuptools wheel
          pip install buildozer cython virtualenv

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: TITAN_APK
          path: bin/*.apk
